### ISSUE TITLE
RESTCONF return type

### ISSUE THREAD

**Issue by sdj38** [clicon/clixon#10]
Olof,

Thanks for your previous fix! It looks good.
Doing some more research and tests I found that GET requests currently will not give the data back as an array if there is only one object in the list. 
For example, using this command `curl -G http://localhost/restconf/data/interfaces-config` While only having one interface in the data store

Should look like

`
{
    "interfaces-config": {
      "interface": [
           {
               "name": "local0"
           }
      ]
    }
  }`
instead of
`
{
    "interfaces-config": {
      "interface": {
        "name": "local0"
      }
    }
}`

I found some examples from the RFC: https://tools.ietf.org/html/rfc8040#section-5.3.2 and here https://tools.ietf.org/html/rfc8040#appendix-B.3.9

This would be helpful when looking at documents if you need to use an array index when parsing the returned JSON. Thank you again for your help on this.

**Comment by olofhagsand** [comment]
Fixed in develop by https://github.com/clicon/clixon/commit/9914847d6a88dd563a4ad88ddaac0f987cf6a94b
