### ISSUE TITLE
simple list model in yang is broken in cligen (in master branch only)

### ISSUE THREAD

**Issue by rombie** [clicon/clixon#106]
CLI> set device d1 
Apr 19 02:34:54: api_path_fmt2api_path: 465: UNIX error: cv2str_dup

module clixon-hello {
    yang-version 1.1;
    namespace "he";
    prefix he;
    revision 2019-04-17 {
        description "Devices objects model";
    }

    list device {
        description "Configure one more devices";
        key "name";
        leaf name {
            type string;
            description "Name of the device";       
        }
    }
}

cvv pointer passed from cligen was NULL (which is for some restconf related variable data holder ?).  Works fine in 4.4.0

**Comment by olofhagsand** [comment]
NULL error problem in CLIgen fixed.  Changed cligen read API to separate EOF from errors. Changed clixon cli code to use the new error/EOF handling.
