### ISSUE TITLE
Once an option is used, other options fail to appear in CLI

### ISSUE THREAD

**Issue by rombie** [clicon/clixon#107]
In yang, if you have say
set fruit mango taste sweet
set fruit mango size big

After first command, second cannot be entered. If a new fruit is selected, then both (size and taste options appear, but not for mango)

this is in master branch. 4.4.0 works correctly

**Comment by olofhagsand** [comment]
As a mitigation you can use USE_CLIGEN44 in clixon to use with previous version of cligen, until I get cligen45 fully backward compatible.

**Comment by olofhagsand** [comment]
This should be fixed by CLIgen bugfix https://github.com/olofhagsand/cligen/commit/6d89c32a8a0313cc7fd8dcb3b56cf7e6883b15e1
Also added testcases.
@rombie can you please verify, I would want to know of any other non-backward-compatible to clixon-44 issues you may detect.

**Comment by olofhagsand** [comment]
Fixed by https://github.com/olofhagsand/cligen/commit/60774d008f563d76f7ea4008fe63dfc7e4936488
Please verify.

**Comment by rombie** [comment]
Thanks. My setup is down at the moment.. I will verify next week.

thanks again!

**Comment by rombie** [comment]
Cool. It works in master branch as expected now

Ty

**Comment by olofhagsand** [comment]
Thanks for reporting and verifying!
