### ISSUE TITLE
How to build the dependency between different modules

### ISSUE THREAD

**Issue by rayshi-10** [clicon/clixon#109]
Hello Olof,
I have two modules like ACL and Interfaces to configure. As the ACL entries will be applied to some Interface, so I need to guarentee the configuration order which ACL is prior to Interfaces while the underlying system is startup. I went through the xml_cmp, however, it seems not to sort/order with this case. Also,RFC7950 doesn't define the schema if I don't miss something.Do you have some suggestions to meet it?
Thanks in advance

**Comment by olofhagsand** [comment]
You want to order your data and apply that to the underlying system in that order?
Following yang, the ordering of items in clixon is described here: https://clixon-docs.readthedocs.io/en/latest/xml.html#sorted-tree
Can you sketch the yang so I understand your usecase a little better? Are your ACLs and interfaces in separate lists?

**Comment by rayshi-10** [comment]
> You want to order your data and apply that to the underlying system in that order?
> Following yang, the ordering of items in clixon is described here: https://clixon-docs.readthedocs.io/en/latest/xml.html#sorted-tree
> Can you sketch the yang so I understand your usecase a little better? Are your ACLs and interfaces in separate lists?

eg.There are two separate YANG specs:
Module acl { //acl.yang
   prefix acl;
   ...
  container acls {
      key id;
      list id {
         ...
     }    
  }
}
Module ietf-interface { // interface.yang
   prefix if;
   ...
  container interfaces {
      key name;
      list name {
         ...
         //Need to apply to **ACL's id** here!
  }
}
so I need to keep the configuration of ACL is prior to interface while the system is startup. 
Thanks

**Comment by olofhagsand** [comment]
Nodes from different modules are sorted in the order the yang files were loaded. For example, if yang module A imports module B, then data symbols from A come before data symbols from B.
But this is only part of the story. The real action is in plugin callbacks you make. If you for example define a commit callback, that callback can get symbols from the XML in any order it needs. It can choose to pick the Interface XML before the ACL:s for example.
In my experience, more important is the internal order of a list, such as the ACL rules, which you may want to have in some significant order.
BTW, you mentioned xml_cmp(). The code for ordering symbols according to yang modules is in yang_order().

**Comment by rayshi-10** [comment]
> Nodes from different modules are sorted in the order the yang files were loaded. For example, if yang module A imports module B, then data symbols from A come before data symbols from B.
> But this is only part of the story. The real action is in plugin callbacks you make. If you for example define a commit callback, that callback can get symbols from the XML in any order it needs. It can choose to pick the Interface XML before the ACL:s for example.
> In my experience, more important is the internal order of a list, such as the ACL rules, which you may want to have in some significant order.
> BTW, you mentioned xml_cmp(). The code for ordering symbols according to yang modules is in yang_order().

Olof,
Got it. Many thanks for your reminder.
Thanks again
