### ISSUE TITLE
GET returns all strings. 

### ISSUE THREAD

**Issue by sdj38** [clicon/clixon#11]
Hi Olof,

Thanks for the previous fix it is working as expected. 
After doing some more tests and broadening my configurations I noticed that all GET requests return everything as a type string. For example 
      {
        "action": "deny",
        "src-last-port": "443", // parsed as type string instead of number -> should be "src-last-port" : 443,
        "dst-last-port": "443",
        "protocol": "tcp"
      }

They should return data based on the YANG type. (string, number, boolean);
Expected value

- Type - String:
{ "string" : **"name"** }

- Type - Number (uint16,uint32...)
{ "number" : **400** }

- Type - boolean
{ "boolean" : **false** }

**Comment by olofhagsand** [comment]
Thanks for detecting this.
Fixed by 2bbf0b8a15941d4f44086df89e4637b6e3216184 in develop
