### ISSUE TITLE
How I can use the restconf?

### ISSUE THREAD

**Issue by dwbxm** [clicon/clixon#122]
I want to use the clixon restconf, but i don't know how to use the restconf according to the document in the site.
Are there other documents about the cilxon restconf?

Thanks.

**Comment by olofhagsand** [comment]
Main documentation is here:
  - https://clixon-docs.readthedocs.io/en/latest/quickstart.html#restconf
More detailed info is here:
  - https://github.com/clicon/clixon/tree/master/apps/restconf
  - https://github.com/clicon/clixon/tree/master/example/main#restconf
Maybe easiest for quick start is docker:
  - https://github.com/clicon/clixon/blob/master/docker/main/README.md

Note that this describes nginx reverse proxy. There is currently also a native http/https implementation using libhtp and openssl 1.1.
