### ISSUE TITLE
Type / Endianism problem in yang_parse_file

### ISSUE THREAD

**Issue by colinmhoward** [clicon/clixon#128]
I have had to cross compile your code onto a processor that is big endian. This causes an issue in the yang_parse_file function, as the read function reads characters into an int, so the character is actully contained in the highest byte of the integer, and then you mask it away as well with an & 0xff.

I have resolved and patched it by getting the read function to read a char instead of an int.

**Comment by olofhagsand** [comment]
Thanks for detecting. Do you have a proposed patch for that?

**Comment by colinmhoward** [comment]
Hi,

Yes, I just changed the variable c in the yang_parse_file function to be a char instead of an int. It fixes the problem and am using that as my patch. 

On 20 Aug 2020, at 14:53, Olof Hagsand <notifications@github.com> wrote:

﻿
Thanks for detecting. Do you have a proposed patch for that?

**Comment by olofhagsand** [comment]
Fixed by patch ^
