### ISSUE TITLE
copy-config's RPC cxobj parameter does not contain namespace 

### ISSUE THREAD

**Issue by Topitzik** [clicon/clixon#131]
copy-config RPC parameters are sent to the BE without namespace attribute (this is probably also the case with other netconf RPCs).
this is in contrast to the example RPCs in CLI client.

**Comment by olofhagsand** [comment]
I interpret this as `xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"` is not provided or expected for top-level constructs. This is because clixon has a compile-time option called: `USE_NETCONF_NS_AS_DEFAULT` which assumes top-level namespaces is the base netconf namespace.
This is wrong and will be changed.

**Comment by olofhagsand** [comment]
Fixed by patch above. Please verify.

**Comment by Topitzik** [comment]
I hope to check this too tomorrow.

**Comment by dima1308** [comment]
@Topitzik did you checked it?

**Comment by Topitzik** [comment]
the logs indeed show that the namespace arrived, but it seems to be stripped from the cxobj provided. 
which means the namespace still can not be known to the RPC callback.

**Comment by olofhagsand** [comment]
Can you please provide some more detail on expected and actual behavior?

**Comment by Topitzik** [comment]
here is an example:
expected cxobj (in main example BE plugin function example_copy_extra this parameter is called 'xe')
`<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" username="root">
<copy-config><source><running/></source><target><startup/></target></copy-config>
</rpc>`
actual behavior:
`<copy-config><target><startup/></target><source><running/></source></copy-config>`
basically the internal netconf RPCs are stripped from the RPC encapsulation (which provide the context like namespace and user) while external RPCs keep this encapsulation.

**Comment by olofhagsand** [comment]
Thats because the callback is called with xe pointing to the rpc instance. If you use its parent, you will get the namespace, eg in gdb:
```
(gdb) p xml_print(stderr, xml_parent(xe))
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" username="olof">
   <copy-config>
      <target>
         <startup/>
      </target>
      <source>
         <running/>
      </source>
   </copy-config>
</rpc>
(gdb) where
#0  from_client_copy_config (h=0x55555576a260, xe=0x555555cb24e0, cbret=0x555555cb7150, 
    arg=0x555555cb2350, regarg=0x0) at backend_client.c:743
#1  0x00007ffff7542321 in rpc_callback_call (h=0x55555576a260, xe=0x555555cb24e0, cbret=0x555555cb7150, 
    arg=0x555555cb2350) at clixon_plugin.c:775
#2  0x0000555555560672 in from_client_msg (h=0x55555576a260, ce=0x555555cb2350, msg=0x555555c90870)
    at backend_client.c:1674
#3  0x0000555555560a1e in from_client (s=5, arg=0x555555cb2350) at backend_client.c:1763
#4  0x00007ffff75178dc in clixon_event_loop () at clixon_event.c:348
#5  0x000055555555c12a in main (argc=0, argv=0x7fffffffe4d0) at backend_main.c:951
```
Also, at this point I usually use the function `xml2ns()` to get the namespace. Eg:
```
(gdb) p xml2ns(xml_parent(xe), 0, &ns)
$9 = 0
(gdb) p ns
$10 = 0x555555cb6940 "urn:ietf:params:xml:ns:netconf:base:1.0"
```

**Comment by Topitzik** [comment]
ohh I didn't know xe had a parent. 
working exactly as you said, 
thanks.

**Comment by olofhagsand** [comment]
I take that as a resolve.
