### ISSUE TITLE
min-elements attribute prevents from deleting list entries

### ISSUE THREAD

**Issue by Topitzik** [clicon/clixon#133]
### problem
min-elements attribute in a list will cause commits to fail when deleting entries, even if enough entries still exist to satisfy the requirement.

### example
consider this simplified Yang model snippet:
```
list people{
	key name;
	leaf name{
		type string;
	}
	min-elements 1;
}
```

running the following sequence of commands will fail:
set people name alice
set people name bob
commit
delete people name bob 
commit **<- will fail**

**Comment by olofhagsand** [comment]
Fixed by patch ^
Please verify.
