### ISSUE TITLE
CLI crash if error-info is empty

### ISSUE THREAD

**Issue by Topitzik** [clicon/clixon#134]
if error-info is empty in rpc-error message, the CLI will crash from segmentation fault.
this does not happen with the other fields (error-type, error-tag, error-severity and error-message).

for example, replying with the following massage will crash:
```
<rpc-reply>
  <rpc-error>
    <error-type>aaa</error-type>
      <error-tag>aaa</error-tag>
      <error-info></error-info>              <---------empty
      <error-severity>aaa</error-severity>
      <error-message>aaa</error-message>
    </rpc-error>
</rpc-reply>
```

also, error-severity is not printed to the user.

**Comment by olofhagsand** [comment]
Fixed by patch. Please verify.

**Comment by Topitzik** [comment]
I will try to get to it tomorrow.
