### ISSUE TITLE
clixon_netconf does not respond to hello

### ISSUE THREAD

**Issue by shmuelhazan** [clicon/clixon#136]
Currently running:
```
clixon_netconf 
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><capabilities><capability>urn:ietf:params:netconf:base:1.0</capability><capability>urn:ietf:params:netconf:base:1.1</capability></capabilities></hello>]]>]]>
```

Does not yield any response. 

get-config rpc seems to work fine. From quick `-D3` lookup, looks like clixon gets the data properly:
```
Dec 12 20:38:05: netconf_input_packet: "<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><capabilities><capability>urn:ietf:params:netconf:base:1.0</capability><capability>urn:ietf:params:netconf:base:1.1</capability></capabilities></hello>"
```

**Comment by shmuelhazan** [comment]
@shmuelnatan FYI

**Comment by shmuelnatan** [comment]
The problem is caused by having `<CLICON_MODULE_LIBRARY_RFC7895>false</CLICON_MODULE_LIBRARY_RFC7895>` in the configuration XML file.

**Comment by olofhagsand** [comment]
Clicon netconf should now issue an hello also when RFC7895 is not loaded.
Please verify.

**Comment by shmuelnatan** [comment]
I verified it, and it works. Thanks.
