### ISSUE TITLE
Slack Invite is expired

### ISSUE THREAD

**Issue by eliwaltuch** [clicon/clixon#139]
Hi All,
The invite link to the clixon Slack channel is expired.
Is it still possible to join?
Thanks,
ELW

**Comment by olofhagsand** [comment]
Try this: https://join.slack.com/t/clixondev/shared_invite/zt-hw9lofnk-C1iDFJ~E_CTiwtyGZi8fdQ

**Comment by eliwaltuch** [comment]
Thanks!

**Comment by nowaits** [comment]
> Try this: https://join.slack.com/t/clixondev/shared_invite/zt-hw9lofnk-C1iDFJ~E_CTiwtyGZi8fdQ

Hi,
    The invite link is expired too, is there new invite link ?
Thanks!
