### ISSUE TITLE
Issues in documentation

### ISSUE THREAD

**Issue by IvanAguiar** [clicon/clixon#141]
Hello,

I'd like to know if the documentation is updated.
I'm trying to install the clixon stack and I'm having many troubles, from dependencies missing to services failing.

I tried in Ubuntu 16.04, on SO and using docker, without success. 

Could you try to help me, please?

BR,

**Comment by olofhagsand** [comment]
Have you looked here?:
[https://clixon-docs.readthedocs.io/en/latest/install.html](https://clixon-docs.readthedocs.io/en/latest/install.html)
Please tell what is not correctly described.
Otherwise run in a docker container, 
or check the vagrant install script for several platforms (freebsd/suse/ubuntu/centos/etc:
[https://github.com/clicon/clixon/blob/master/test/vagrant/vagrant.sh](https://github.com/clicon/clixon/blob/master/test/vagrant/vagrant.sh)

**Comment by IvanAguiar95** [comment]
Yes, I try to use the official documentation.
I'm using a clean Ubuntu 16.04 VM, and I got some issues like:

- sudo apt-get install fcgi-dev nginx (**fcgi-dev** is not a known package, in the documentation it's not requiring any repository for example, works using **libfcgi-dev**)
- sudo apt-get install libevent-2.1  (**libevent-2.1** is not a known package, **libevent-dev** doesn't work)

And others.

I was able to use the stack when I did clone, and build the docker container directly from source, using the dockerhub do not work as well (the docker container never up).

**Comment by olofhagsand** [comment]
OK, thanks for input. I went through some ubuntu releases to see the packages and I have updated the installation instructions to that, please see https://clixon-docs.readthedocs.io/en/latest/install.html
I did a small survey of libevent and fcgi on ubuntu releases and got this. To me libevent-dev worked on all, but fcgi may need to be built from source for some:

Description:    Ubuntu 12.04 LTS
Release:        12.04
Codename:       precise
libfcgi-dev
libevent-dev # loads libevent-2.0-5

Description:    Ubuntu 14.04.6 LTS
Release:        14.04
Codename:       trusty
libfcgi-dev
libevent-dev # loads libevent-2.0-5

Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
libfcgi-dev
libevent-dev # loads libevent-2.0-5

Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
# fcgi not found
libevent-dev # loads libevent-2.1

Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
# fcgi not found
libevent-dev # loads libevent-2.1-7

**Comment by IvanAguiar95** [comment]
Ok @olofhagsand, thank you for your help.

I'll try to configure again, and I'll let you know if I have any troubles.

BR,
