### ISSUE TITLE
CLixon not able to launch clixon.xml in /usr/local/etc/ 

### ISSUE THREAD

**Issue by KunwarAkanksha** [clicon/clixon#142]
In URL https://clixon-docs.readthedocs.io/en/latest/install.html
The first step to clone the clixon is correct or not ?
I guess it should be : 
**git clone https://github.com/clicon/clixon.git**
Cause installation using  **git clone https://github.com/clicon/cligen.git**  is not matching to the commands that are referred in quick start tab.
 
Though After Installing the clixon there is no clixon.xml file in  /usr/local/etc/ , so the error encountered is : 
 sudo clixon_backend 
Oct  7 11:26:38: parse_configfile: 304: UNIX error: /usr/local/etc/clixon.xml: No such file or directory
Oct  7 11:26:38: clixon_backend: 19141 Terminated retval:-1

Please tell me what may have went wrong

**Comment by olofhagsand** [comment]
cligen is a prerequisite. Building, configuring, and installing clixon is made in section "build from source", but you are right, that section is missing a `git clone https://github.com/clicon/clixon.git` statement.
You may also need to start clixon with an explicit `-f /usr/local/etc/example.xml` command-line.
Thanks for feedback.
