### ISSUE TITLE
namespace prefix nc is not supported

### ISSUE THREAD

**Issue by dima1308** [clicon/clixon#143]
I tried to use a python script to communicate with CLIXON based device (I used ncclient library for that).
I saw that the CLIXON does not support XML namespace tag nc and reject well-formatted messages with nc namespace prefix

Is it possible to fix it?

Note: I found a workaround - to use the following ncclient manager configuration:
```
manager.connect(host=host,
                           port=port,
                           username=user,
                           password=password,
                           hostkey_verify=False,
                           device_params={'name': 'ericsson', 'with_ns': False},
                           allow_agent=False,
                           look_for_keys=False)
```
I added line `device_params={'name': 'ericsson', 'with_ns': False}` to accept XML without nc namespace

**Comment by olofhagsand** [comment]
I am not familiar with the python lib (ncclient) but it would be very good to support that.
I need some more details though. Can you see which message goes on the "wire" between nccleint and clixon, eg which netconf message on the form `<rpc><...`.
I suspect (but may be wrong) that the "nc" prefix may be hardwired without a `xmlns="..."` statement in the rpc?

**Comment by dima1308** [comment]
@olofhagsand please see attached logs. Without the patch, you can see tags like <nc:source>. But with the patch, you can see tags like <source>
[no_patch.txt](https://github.com/clicon/clixon/files/5378404/no_patch.txt)
[with_patch.txt](https://github.com/clicon/clixon/files/5378405/with_patch.txt)

**Comment by olofhagsand** [comment]
Thanks, will look into it.

**Comment by olofhagsand** [comment]
Fixed by patch ^.
Please verify.

**Comment by dima1308** [comment]
Checking... will update you

**Comment by dima1308** [comment]
@olofhagsand I validated the fix, closing the bug.
