### ISSUE TITLE
Bytewise read() of files is slow

### ISSUE THREAD

**Issue by hjelmeland** [clicon/clixon#146]
By changing to buffered read in  yang_parse_file(), I reduced the startup time of clixon_backend to a fifth. In the test I loaded many large YANG models, but only a small data store. I only tested on PC for now, getting a speed up of 200 ms. On a slow target, I suspect improvement can be seconds. 

For the test I just did a fp=fdopen(fd, "r"); and then replaced the read with fread( &c, 1, 1, fp)). I think it would be best to change the API so that yang_parse_file(), clixon_xml_parse_file() and clixon_json_parse_file() gets a FILE* instead of a int file descriptor. But I don't know if you like to change the API.

**Comment by olofhagsand** [comment]
Thanks for looking into this. I need to look at the API.

**Comment by olofhagsand** [comment]
Confirm it gives ~16 x improvement on large xml files.
I see it as doable as changing the API, these are not typically exposed functions, at least not in the application I have insight.

**Comment by olofhagsand** [comment]
Fixed by patch ^
