### ISSUE TITLE
YANG: key statement in rpc/notification list

### ISSUE THREAD

**Issue by hjelmeland** [clicon/clixon#148]
Clixon require key statement in lists inside rpc and notification. AFAIKT RFC only require key statement for configuration data.

**Comment by olofhagsand** [comment]
@hjelmeland  the fix ^ addresses the sub-error:
* Do not check uniqueness (of XML) among lists without keys
As far as I can see, key-less lists were/are allowed in YANG for state/notification/rpc.
The error I could find was that XML of such lists were checked for non-uniqueness, as if they had keys.
Please come back with an example testcase that fails if this fix does not work.
