### ISSUE TITLE
False Header Content_type in restconf error

### ISSUE THREAD

**Issue by idefixcert** [clicon/clixon#152]
If we post a false restconf configuration:

the result is are 2 header with content type:
< Content-Type: text/plain; charset=utf-8
< Content_type: application/yang-data+json

I think the Content_type resides form this code path here:
https://github.com/clicon/clixon/blob/73bbcded87c2973ea5394fdd5a98ecf8dc3aab13/apps/restconf/restconf_err.c#L430

**Comment by olofhagsand** [comment]
Thank you for reporting errors.
