### ISSUE TITLE
namespace prefix nc is not supported in full

### ISSUE THREAD

**Issue by dima1308** [clicon/clixon#154]
Hi @olofhagsand 
It looks the https://github.com/clicon/clixon/issues/143 issue is not solved in full.
Please see attached two logs
[good-no-ns.txt](https://github.com/clicon/clixon/files/5612576/good-no-ns.txt)
[bad-with-ns.txt](https://github.com/clicon/clixon/files/5612577/bad-with-ns.txt)
The good-no-ns.txt file shows the test result when a namespace is not allowed.
The bad-with-ns.txt file shows the test result when a namespace is allowed and we get a timeout.
Can you please compare both files? You will see that some netconf messages have ns namespace and some messages don't have it.

**Comment by olofhagsand** [comment]
bad:
```
<nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:3f90651b-25a7-4ebf-97bb-8c4af5f871bc"> <nc:edit-config><nc:target><nc:candidate/></nc:target><config>
```
config lacks prefix `config" -> nc:config`
Or do has in good, use default prefix:
```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:03ad5f23-b03b-4a3c-927f-37f473ad92bc"><edit-config><target><candidate/></target><config>
```

**Comment by olofhagsand** [comment]
I also see: `"Could not find 'message-id' attribute in <rpc-reply>"`

**Comment by dima1308** [comment]
1. In good, I configured the client not to use prefix at all.
2. I think, the `"Could not find 'message-id' attribute in <rpc-reply>"` error caused by the previous `bad-element` error.

**Comment by olofhagsand** [comment]
> In good, I configured the client not to use prefix at all.

I am unsure what you mean?
(1) In "bad",  ^the `<config> ` tag lacks a namespace prefix. Is this something generated by clixon? I thought it was generated by the external tool and clixon reacts with an error message, that in turn (2) seem to get an error from the tool in that it does not have a message-id attribute.
I am looking at (2) adding message-id in errors - which I can confirm is an clixon issue.
But I dont know what to do about (1) - it seems generated outside of clixon.  Please inform.

**Comment by dima1308** [comment]
@olofhagsand my mistake... In "good" I configured not to use the prefix. Sorry.

**Comment by dima1308** [comment]
<config> is coming from my sample code. Should it be changed to <nc:config>?

**Comment by olofhagsand** [comment]
Yes, or set a default namespace as <rpc xmlns=...> , in the current setup there is no default namespace, therefore <config> namespace is void.

**Comment by dima1308** [comment]
I tried to use XML like this - it does not work with nc namespace... What I did wrong?
`<nc:config>
   <ip xmlns="http://siklu.com/yang/tg/ip">
      <ipv4>
         <address>
            <ip>2.2.2.2</ip>
         </address>
      </ipv4>
   </ip>
</nc:config>`

**Comment by olofhagsand** [comment]
The "nc" prefix must be declared somewhere. ie as <nc:rpc xmlns:nc="..."
The base reference for all this is https://www.w3.org/TR/2009/REC-xml-names-20091208/

**Comment by olofhagsand** [comment]
Added message-id:s in replies according to fix above.
@dima1308: is there anything remaining in the ticket, or can it be closed?

**Comment by dima1308** [comment]
@olofhagsand thanks for the fast response. Please let me test it with the latest master

**Comment by dima1308** [comment]
@olofhagsand I'm using the latest CLIXON master trying to send the following XML:
```
<nc:config xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
   <ip xmlns="http://siklu.com/yang/tg/ip">
      <ipv4>
         <address>
            <ip>2.2.2.2</ip>
         </address>
      </ipv4>
   </ip>
</nc:config>
```
I got an error  - please see attached log.
[new_try.txt](https://github.com/clicon/clixon/files/5625093/new_try.txt)
This is something I did wrong or it is a bug in CLIXON?

**Comment by olofhagsand** [comment]
```
<?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:44f66517-6f26-4d43-aa25-92838f700528"><nc:edit-config><nc:target><nc:candidate/></nc:target><nc:config>
   <ip xmlns="http://siklu.com/yang/tg/ip">
      <ipv4>
         <address>
            <ip>2.2.2.2</ip>
         </address>
      </ipv4>
   </ip>
</nc:config></nc:edit-config></nc:rpc>]]>]]>
```
The above seems ok, it _may_ be a clixon problem, but I need to check. 
Please try a default namespace, eg: 
```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:44f66517-6f26-4d43-aa25-92838f700528"><edit-config><target><candidate/></target><config>
  ...
```

**Comment by dima1308** [comment]
Please see attached 2 additional tries I did
[try1.txt](https://github.com/clicon/clixon/files/5625182/try1.txt)
[try2.txt](https://github.com/clicon/clixon/files/5625181/try2.txt)

**Comment by olofhagsand** [comment]
Added a patch to fix the problem of <nc:config> appearing with tag other than null/default.
Hope this fixes your issues.

**Comment by dima1308** [comment]
I tried the latest version. I can send XML with namespace, please see the example below
```
<nc:config xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
   <ip xmlns="http://siklu.com/yang/tg/ip">
      <ipv4>
         <address>
            <ip>2.2.2.2</ip>
         </address>
      </ipv4>
   </ip>
</nc:config>
```
If I remove the namespace from `config`, it does not work. Is it an expected result?

**Comment by olofhagsand** [comment]
Yes, because there is no default namespace declared: 
there is no `xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"` in that context.

**Comment by dima1308** [comment]
@olofhagsand thanks for the fast response. Tomorrow I plan to run more tests with the latest CLIXON master and will update you.

**Comment by olofhagsand** [comment]
I hope it works with :1.0? I dont recognize :1.1, where is that defined?

**Comment by dima1308** [comment]
yes, 1.0 is working well. The client I use support 1.1. So, I expect that the command will work. Am I missing something?

**Comment by olofhagsand** [comment]
I have seen examples using urn:ietf:params:xml:ns:netconf:base:1.1
But I have seen no formal documents using it, therefore it is not supported in clixon.
You could help by finding a definition of urn:ietf:params:xml:ns:netconf:base:1.1.
I may have missed it.

**Comment by dima1308** [comment]
I can try to run netconf requests against the 1.1 device and see which commands are transmitted. Will it help?

**Comment by olofhagsand** [comment]
Sure, to see differences from 1.0. 
Maybe it would help even more if you could find some docs or references on 1.1

**Comment by dima1308** [comment]
OK, I will try. I will close this bug. 
When I will have info about 1.1 - I will update you.
