### ISSUE TITLE
RESTCONF /operations

### ISSUE THREAD

**Issue by sdj38** [clicon/clixon#16]
Hi Olof,
After some testing, it was brought to my attention that the /operations endpoint should provide a list of possible RPC operations. Here is the RFC reference https://tools.ietf.org/html/rfc8040#section-3.3.2 

Here is the example I was given of what it should look like.
``` 
The expected result for "operations":
$ curl -X GET http://localhost/restconf/operations

{
  "operations" : { 
     "netgate-system:system-running-to-startup" : [null],
     "netgate-frr:frr-control" : [null],
     "netgate-frr:frr-daemons-gen-config" : [null],
     "netgate-kea:kea-control" : [null],
     "netgate-vpp:vpp-control" : [null],
     "netgate-bgp:bgp-gen-config" : [null],
  }
}
```

Currently, it returns a 502 error.

There is an example of a request and response in this section https://tools.ietf.org/html/rfc8040#section-3.1

```
The client might send the following:

      GET /top/restconf/operations HTTP/1.1
      Host: example.com
      Accept: application/yang-data+json

   The server might respond as follows:

      HTTP/1.1 200 OK
      Date: Thu, 26 Jan 2017 20:56:30 GMT
      Server: example-server
      Cache-Control: no-cache
      Last-Modified: Thu, 26 Jan 2017 16:00:14 GMT
      Content-Type: application/yang-data+json

      { "operations" : { "example-jukebox:play" : [null] } }
```
Thank you for your help with this.

**Comment by olofhagsand** [comment]
Added this functionality. Except, the example above is returned as:
   { "operations" : { "example-jukebox:play" : null } }
I don't see the logic of [null], why would it be an array?

**Comment by sdj38** [comment]
Yeah, I can't find any examples or reason why they show it returning an array.
