### ISSUE TITLE
Strict auto completion for CLI argument expansion

### ISSUE THREAD

**Issue by rohitrajskk** [clicon/clixon#163]
CLI argument should not accept any string other than strings from the expansion list.

This can be implemented using autocli-op as explained below by olof.

The problem being that the autocli currently generates something like the following code:
  cmd (<enabled:bool>|<enabled:bool expand_dbvar("candidate","/...")>
where enabled is either expanded from a known (strict) list of commands or any string. What I think you want is the ability to remove the "any" option as follows:
  cmd (<enabled:bool expand_dbvar("candidate","/...")>
It is possible in the cli with manual use, but currently not in autocli.
However, this would be a good case of the newly introduced autocli-op extension recently introduced for "hidden commands" as described here https://clixon-docs.readthedocs.io/en/latest/cli.html#hidden-commands with maybe something like:
  cl:autocli-op expand-strict;
or something similar.

**Comment by olofhagsand** [comment]
This should now work. Mark a leaf with extension `autocli:strict-expand`:
```
      leaf value{
        autocli:strict-expand;
        type string;
      }
```
See also
* https://clixon-docs.readthedocs.io/en/latest/cli.html#yang-extensions 
* https://github.com/clicon/clixon/blob/master/test/test_autocli_strict_expand.sh

@rohitrajskk  Please verify the functionality!
