### ISSUE TITLE
Cannot retrieve all(multiple) instances of a list while it is possible for a container

### ISSUE THREAD

**Issue by DeekshaBhandary** [clicon/clixon#170]
[
[yang_details.txt](https://github.com/clicon/clixon/files/5833781/yang_details.txt)
](url)

Hi, 
    i have attached a reference yang data for explanation purpose.
For an example as above, the cli tree that gets generated for a **container** will be as follows:
```
> show config cont  ?
<cr>
leaf1      <some helptext>
leaf2      <some helptext>
leaf3      <some helptext>
```
So by executing a command like "show config cotainer <cr>" will retrieve all instances of container configs.

Whereas the cli tree that gets generated for a **list** will be as follows:
```
> show config list1  ?
leaf1      <some helptext>                  _<----- no <cr> present_
leaf2      <some helptext>
leaf3      <some helptext>
```
Hence it is not possible to retrieve all instances of list1 and a leaf attribute has to be specified.

I looked into the func **yang2cli_container** and noticed the callback is generated in case of container before looping through the leaf nodes whereas in **yang2cli_list**  the callback is generated after looping through each leaf node while constructing the cli tree which causes this difference in behavior.

Is it possible to have a common behavior across container and list?

**Comment by olofhagsand** [comment]
The issue formulation needs to be more precise, please assist to see if this is how you mean.
First, adjust the yang somewhat: No key in container, a top-level container referencing cont and list1:
```
    grouping group1{
	list list1 {
	    key "leaf1";
	    leaf leaf1 { type string; }
	    leaf leaf2 { type string; }
	    leaf leaf3 { type string; }
	}	
    }
    grouping group2{
	container cont {
	    leaf leaf1 { type string; }
	    leaf leaf2 { type string; }
	    leaf leaf3 { type string; }
	}	
    }
    container top {
	uses group1;
	uses group2;
    }
```
Then a config is set:
```
> set top cont leaf1 a
> set top cont leaf2 b
> set top cont leaf3 c
> set top list1 a
> set top list1 a leaf2 b
> set top list1 a leaf2 c
```
Which yields the following config db:
```
<config>
   <top xmlns="urn:example:clixon">
      <list1>
         <leaf1>a</leaf1>
         <leaf2>c</leaf2>
      </list1>
      <cont>
         <leaf1>a</leaf1>
         <leaf2>a</leaf2>
         <leaf3>a</leaf3>
      </cont>
   </top>
</config>
```
The next issue is that there are currently several variants of the C-API for the auto-cli:
1. `show conf, cli_auto_show("datamodel", "candidate", "text", true, false);` This is currently the only variant documented in clixon-docs, see https://clixon-docs.readthedocs.io/en/latest/cli.html#the-auto-cli)
2. `show conf, cli_show_config("candidate", "text", "/");`
3. `show conf @datamodel, cli_show_auto("candidate", "text");` 
4. `show conf @datamodelshow, cli_show_auto("candidate", "text");` 

Then there is also the clixon options:
CLICON_CLI_GENMODEL_TYPE with values: NONE, VARS, ALL, HIDE

Assume (3) above, for example:
```
cli> show conf top list1 
  a                    
  <leaf1>   
cli>     
```
Please clarify the issue given this framework?

**Comment by DeekshaBhandary** [comment]
Hi Olaf,
            With this framework, you will notice that it is possible to execute a command such as
```
cli>  show config top cont
<cr>
leaf1
leaf2
leaf3
cli>
```
The above command on execution retrieves all container configs but it not possible to do the same with list: we need to specify a leaf node
```
cli>  show config top list1
leaf1
leaf2
leaf3
cli>
```


Is the issue clear?

**Comment by olofhagsand** [comment]
No not quite, I would like to understand which show command you are using. Which one of:

1. show conf, cli_auto_show("datamodel", "candidate", "text", true, false); This is currently the only variant documented in clixon-docs, see https://clixon-docs.readthedocs.io/en/latest/cli.html#the-auto-cli)
2. show conf, cli_show_config("candidate", "text", "/");
3. show conf @datamodel, cli_show_auto("candidate", "text");
4. show conf @datamodelshow, cli_show_auto("candidate", "text");

Using the config above, and doing `show conf top cont vs list1 ?` using (3) above, I get the following:
```
olof@alarik /> show conf top list1 
  a                    
  <leaf1>    
```
Using (4), I get the following:
```
olof@alarik /> show conf top list1 
  <cr>
  a                    
  <leaf1>  
```
Can you please tell me which cli "show config" syntax you use (out of 1-4)?

**Comment by DeekshaBhandary** [comment]
I currently use the syntax 3:
show config @treename , cli_show_auto("running", "text");

**Comment by DeekshaBhandary** [comment]
Closing this issue as of now as it can be solved by referring a secondary tree @datamodelshow for 'show' command purpose
