### ISSUE TITLE
default values of strings aren't generated when defined in typedef

### ISSUE THREAD

**Issue by shmuelnatan** [clicon/clixon#172]
Default string values aren't generated into configuration if they're defined in the typedef itself. In the following case there's no default value that's generated for name: 
`typedef type-name {
         type string;
         default "smith";
}
leaf name {
        type type-name;
}`

But, when the default isn't in the typedef, then it is generated into the configuration. In the following case there's a default value that's generated for name:
`typedef type-name {
         type string;
}
leaf name {
        type type-name;
        default "smith";
}`

We saw this bug with string types. We also saw that this bug doesn't happen with enumeration types.

**Comment by olofhagsand** [comment]
Cannot recreate the problem.
Example yang:
```
    typedef type-name1 {
	type string;
	default "andersson";
    }
    typedef type-name2 {
	type string;
    }
    leaf name1 {
	type type-name1;
    }
    leaf name2 {
	type type-name2;
	default "smith";
    }
```
Then run show the configuration:
```
olof@alarik> clixon_cli -f /usr/local/etc/example.xml
olof@alarik /> show configuration xml
<name1 xmlns="urn:example:clixon">andersson</name1>
<name2 xmlns="urn:example:clixon">smith</name2>
olof@alarik /> 
```
Checked this in 4.9.0 and master (4.10.0.pre)

**Comment by shmuelnatan** [comment]
Maybe try only a leaf with the problem, such as
 `typedef type-name1 {
	type string;
	default "andersson";
    }
    leaf name1 {
	type type-name1;
    }`

**Comment by olofhagsand** [comment]
I tried with the following yang:
```
module clixon-example {
    yang-version 1.1;
    namespace "urn:example:clixon";
    prefix ex;
    revision 2020-12-01 {
	description "Added table/paramater/value as the primary data example";
    }
    typedef type-name1 { type string; default "andersson"; } leaf name1 { type type-name1; }
}
```
And the following clispec:
```
CLICON_MODE="example";
CLICON_PROMPT="%U@%H %W> ";
CLICON_PLUGIN="example_cli";

show configuration("Show configuration"), cli_show_config("candidate", "text", "/");
```
with the example.xml as in example/main/example.xml:
```
<clixon-config xmlns="http://clicon.org/config">
  <CLICON_CONFIGFILE>/usr/local/etc/example.xml</CLICON_CONFIGFILE>
  <CLICON_FEATURE>ietf-netconf:startup</CLICON_FEATURE>
  <CLICON_YANG_DIR>/usr/local/share/clixon</CLICON_YANG_DIR>
  <CLICON_YANG_MODULE_MAIN>clixon-example</CLICON_YANG_MODULE_MAIN>
  <CLICON_CLI_MODE>example</CLICON_CLI_MODE>
  <CLICON_BACKEND_DIR>/usr/local/lib/example/backend</CLICON_BACKEND_DIR>
  <CLICON_NETCONF_DIR>/usr/local/lib/example/netconf</CLICON_NETCONF_DIR>
  <CLICON_RESTCONF_DIR>/usr/local/lib/example/restconf</CLICON_RESTCONF_DIR>
  <CLICON_CLI_DIR>/usr/local/lib/example/cli</CLICON_CLI_DIR>
  <CLICON_CLISPEC_DIR>/usr/local/lib/example/clispec</CLICON_CLISPEC_DIR>
  <CLICON_SOCK>/usr/local/var/example/example.sock</CLICON_SOCK>
  <CLICON_BACKEND_PIDFILE>/usr/local/var/example/example.pidfile</CLICON_BACKEND_PIDFILE>
  <CLICON_CLI_GENMODEL_COMPLETION>1</CLICON_CLI_GENMODEL_COMPLETION>
  <CLICON_CLI_GENMODEL_TYPE>VARS</CLICON_CLI_GENMODEL_TYPE>
  <CLICON_XMLDB_DIR>/usr/local/var/example</CLICON_XMLDB_DIR>
  <CLICON_CLI_LINESCROLLING>0</CLICON_CLI_LINESCROLLING>
  <CLICON_STARTUP_MODE>init</CLICON_STARTUP_MODE>
  <CLICON_NACM_MODE>disabled</CLICON_NACM_MODE>
  <CLICON_STREAM_DISCOVERY_RFC5277>true</CLICON_STREAM_DISCOVERY_RFC5277>
  <CLICON_MODULE_LIBRARY_RFC7895>false</CLICON_MODULE_LIBRARY_RFC7895>
</clixon-config>
```
And a cli run:
```
olof@alarik> clixon_cli -f /usr/local/etc/example.xml     
olof@alarik /> show configuration 
name1 andersson;
olof@alarik /> 
```

**Comment by shmuelnatan** [comment]
So I guess that my evaluation of the origin of the bug is wrong. Our full case where the bug originates is the following yang file. 

`module bug {   

    // typedef statements
    typedef name-1 {
        type string {
            length "8..32";
        }
	default "Smithsonian" 
    }

    typedef name-2 {
        type string {
            length "8..32";
        }
	default "Smithsonian" 
    }
	
    // grouping statements
    grouping top {
        container c-top {
            container c-c-top {
                uses g-name;
            }
        }
    }
	
    grouping g-name {
        leaf l-g-name-1 {
            type name-1;
        }
	leaf l-g-name-2 {
            type name-2;
        }
    }

    grouping g-top {
        container c-g-top {
            uses top;
        }
    }

    uses g-top;
}
`
Our example.xml file is similar to yours, besides that we also have added the following field 
`  <CLICON_CLI_GENMODEL>2</CLICON_CLI_GENMODEL>
`

**Comment by olofhagsand** [comment]
I tried with the value of 2, but again cannot recreate it.
I would be interested in if you could recreate it. 
If not, can it be closed?
