### ISSUE TITLE
Is there an error with plugin's ca_interrupt setting ?

### ISSUE THREAD

**Issue by nowaits** [clicon/clixon#173]
https://github.com/clicon/clixon/blob/1f0147f996fe825af4f88aee1c60ee6f79bbe3c0/apps/cli/cli_plugin.c#L463

_cli_susp_hook(h, fns)_ should be replace by _cli_interrupt_hook(h, fni)_

**Comment by olofhagsand** [comment]
Here is a slack invite
https://join.slack.com/t/clixondev/shared_invite/zt-l36yx3fp-Lmi3qJGQyu5PEC~Zxi2Z5Q

**Comment by nowaits** [comment]
Thanks!

**Comment by olofhagsand** [comment]
Thanks fo reporting
