### ISSUE TITLE
Irregular ordering of cli command + help text when integer is a part of command

### ISSUE THREAD

**Issue by DeekshaBhandary** [clicon/clixon#176]
Looks like string comparison is being done is for all data types.
ex : content of .cli file:
test("Example command") {
1("one"), some_func();
2("two"), some_func();
11("eleven"), some_func();
33("thirty three"), some_func();
22("twenty two"), some_func();
}
cli generated
```
cfg> test
  1                     one
  11                   eleven      
  2                     two
  22                    twenty two
  33                    thirty three
cfg>
```
Instead is it possible to have output like(normal sort in integers)
```
cfg> test
  1                     one
  2                     two
  11                   eleven      
  22                    twenty two
  33                    thirty three
cfg>
```

**Comment by olofhagsand** [comment]
Enabled by default `cligen_lexicalorder_set()` using strversmp instead of strcmp
