### ISSUE TITLE
database stays locked when SSH connection closes

### ISSUE THREAD

**Issue by shmuelnatan** [clicon/clixon#177]
If a user connects to CLI through SSH and locks the database, and then he closes the SSH connection (without unlocking the database) - then the database stays locked, and he can't unlock it.

**Comment by olofhagsand** [comment]
Changed that behavior recently. Do you have some more details?

**Comment by shmuelnatan** [comment]
You changed it after 4.9.0? (This bug happens in that version)

**Comment by olofhagsand** [comment]
Yes here:
https://github.com/clicon/clixon/commit/f5f013c7392f1cf6763266ac851330727ad65cc5
It would be interesting to see if you see this behavior in master / after that commit.
