### ISSUE TITLE
RFC 6241

### ISSUE THREAD

**Issue by s-bauer** [clicon/clixon#185]
README in the netconf code states "[...] needs to be updated to RFC 6241 and RFC 6242." (https://github.com/clicon/clixon/blob/c2f07fd29c9eea540d9e7ef8ccb3cff5e3a1d237/apps/netconf/README.md).

In the Docs (https://clixon-docs.readthedocs.io/en/latest/standards.html#netconf) however, you state that both RFC 6241 and 6242 are supported. 

I guess the README should be updated. Leaving this issue as a note for you :)

**Comment by olofhagsand** [comment]
the README was outdated, replaced with a reference to clixon-docs.
