### ISSUE TITLE
clixon_restconf not properly configed and started by clixon_backend

### ISSUE THREAD

**Issue by nowaits** [clicon/clixon#193]
hi olof,

Currently if want to start clixon_restconf separately, I need add `restconf` config to config.xml like this:
```
<clixon-config>
...
  <restconf>
    <enable>true</enable>
    <auth-type>none</auth-type>
    <debug>0</debug>
    <pretty>true</pretty>
    <fcgi-socket>/www/fastcgi_restconf.sock</fcgi-socket>
  </restconf>
</clixon-config>
```

if i need to start clixon_restconf by clixon_backend, i have to both change config.xml and startup_db.
```
<clixon-config>
...
  <restconf>
    <enable>true</enable>
    <auth-type>none</auth-type>
    <debug>0</debug>
    <pretty>true</pretty>
    <fcgi-socket>/www/fastcgi_restconf.sock</fcgi-socket>
  </restconf>
</clixon-config>
```
```
<configuration>
  ...
   <restconf xmlns="http://clicon.org/restconf">
      <enable>true</enable>
      <fcgi-socket>/www/fastcgi_restconf2.sock</fcgi-socket>
   </restconf>
</configuration>
```
when clixon_restconf started, only config in config.xml take effect.
if i remove config in config.xml, the clixon_restconf will not started by clixon_backend.

https://github.com/clicon/clixon/blob/43db8dd5c566a1eb30544ef22743d8556b18638e/apps/restconf/restconf_main_fcgi.c#L471
xrestconf1 should be xrestconf2

**Comment by olofhagsand** [comment]
Fixed the bug described at the end.
I am unsure if there is something else you seem to be not working?
