### ISSUE TITLE
cli will hang in match_complete with CLICON_CLI_TAB_MODE equal 4

### ISSUE THREAD

**Issue by nowaits** [clicon/clixon#196]
add CLICON_CLI_TAB_MODE 4 to config.xml as blow:
```
<clixon-config xmlns="http://clicon.org/config">
  <CLICON_CLI_TAB_MODE>4</CLICON_CLI_TAB_MODE>
</clixon-config>
```
in cli, first input `e`, and then <tab>, cli will stuck in match_complete and never break
```
root@localhost.localdomain />e 
```

**Comment by olofhagsand** [comment]
The TAB flags are not tested by regressions, only 0.
If they are available they should be tested. But since they are not they seem to have stopped working, at least flag 4. 
So either they should be tested or they should be removed.
Do you think TAB = 4 is useful? do you need it in the application?
```
/* Steps to complete
 * 0: complete single step. 1: complete all steps at once
 */
#define CLIGEN_TABMODE_STEPS    0x04
```

**Comment by olofhagsand** [comment]
Fixed please verify
