### ISSUE TITLE
making cli_show_options's output more human readable 

### ISSUE THREAD

**Issue by nowaits** [clicon/clixon#199]
Hi olof, 
add '\n' for fprintf with the following two line will make the ouput more human readable.
https://github.com/clicon/clixon/blob/0020c7ff3f4865d28bc9dfc83974c9cc344e4812/apps/cli/cli_show.c#L880
https://github.com/clicon/clixon/blob/0020c7ff3f4865d28bc9dfc83974c9cc344e4812/apps/cli/cli_show.c#L889

**Comment by olofhagsand** [comment]
Submitted a patch, please review

**Comment by nowaits** [comment]
hi olof, line 889 shoud also add '\n'
https://github.com/clicon/clixon/blob/0020c7ff3f4865d28bc9dfc83974c9cc344e4812/apps/cli/cli_show.c#L889

**Comment by olofhagsand** [comment]
Fixed again, please verify
