### ISSUE TITLE
unable change leaf value when edit path reach to a leaf

### ISSUE THREAD

**Issue by nowaits** [clicon/clixon#201]
hi olof, there is astrange behavior with cli_auto_edit and cli_auto_set.
my yang file as below:
```
module unigw {
...
    container a {
        leaf b {
            type string;
        }
    }
...
```
and in cli i input `edit a b`, it suggest me input more data,
when inputing `edit a b xxx`, there is no way to change `b` value
```
root@localhost.localdomain /> edit a b
CLI syntax error: "edit a b": Incomplete command
root@localhost.localdomain /> edit a b xxx
root@localhost.localdomain /unigw:a/b> set xxx
CLI syntax error: "set xxx": Unknown command
root@localhost.localdomain /unigw:a/b> 
```
there may be a logic error.

**Comment by olofhagsand** [comment]
The edit command is inspired by junos mode handling. "Edit" should maybe be renamed "Mode". It applies only to non-leafs, eg to lists and containers. You can enter an edit mode for a since it is a container, but not for a b since it is a leaf.
Example:
```
olof@alarik /> set a b foo
olof@alarik /> sh
 shell                show                
olof@alarik /> show configuration 
a {
    b foo;
}
olof@alarik /> edit a 
olof@alarik /clixon-example:a> sh
 shell                show                
olof@alarik /clixon-example:a> show configuration 
b foo;
olof@alarik /clixon-example:a> set b bar
olof@alarik /clixon-example:a> sh
 shell                show                
olof@alarik /clixon-example:a> show configuration 
b bar;
olof@alarik /clixon-example:a> up
olof@alarik /> sh
 shell                show                
olof@alarik /> show configuration 
a {
    b bar;
}
olof@alarik /> 
```

**Comment by nowaits** [comment]
There maybe should throw an error when inputing command like this `edit a b xxx`, and give the error info link `CLI syntax error: "edit a b xxx": edit cann't handle no-leaf path`

**Comment by olofhagsand** [comment]
Ah yes, didnt see that, thanks.

**Comment by nowaits** [comment]
And when inputing `edit a` then TAB,  there shouldn't be auto completion for no-leaf element. if inputing a no-leaf command, there should throw an error.

**Comment by olofhagsand** [comment]
This may need a larger take, will have to wait to after 5.1. Thanks for reporting.

**Comment by nowaits** [comment]
This issue was fixed by now, but there has new issue.
The cli `up, cli_auto_up("datamodel");` seems did not work.

**Comment by olofhagsand** [comment]
The edit-modes has changed API in 5.5 see https://clixon-docs.readthedocs.io/en/latest/cli.html#edit-modes
It should be changed to something like:
`up, cli_auto_up("basemodel");`
