### ISSUE TITLE
xml child ordering

### ISSUE THREAD

**Issue by medvedv** [clicon/clixon#22]
Hi Olof,

 I have a simple yang like:
... 
              list filter {
                        key name;
                        ordered-by user;
                        description "Define a firewall filter";
                        leaf name {
                                description "Filter name";
                                type string;
                        }
...
When I do in cli
set filter %name%
it appends to the end of a list.
It would be great if if it will be possible to insert node in an arbitrary place (before or after existing nodes)
Thanks in advance!

**Comment by olofhagsand** [comment]
Yes, for that I need to add yang insert attributes in netconf edit-config according to RFC 7950 Sections 7.7.9 and 7.8.6. And add the restonf support.
It should be added but is not completely trivial.

**Comment by olofhagsand** [comment]
This was added to Clixon 4.1.0, see https://github.com/clicon/clixon/blob/master/CHANGELOG.md#410
