### ISSUE TITLE
xpath_first search issue

### ISSUE THREAD

**Issue by nowaits** [clicon/clixon#222]
hi olof, xpath_first has an search issue.
My test code like this:
```
int
test_xpath_first()
{
    int retval = -1;
    cxobj *xt = NULL;
    cxobj *xerr = NULL;
    cxobj *eth1;
    cxobj *x1, *x2;
    if (clixon_xml_parse_string(" \
            <interfaces> \
                <interface> \
                    <name>eth0</name> \
                    <type>ianaift:softwareLoopback</type> \
                    <ipv4> \
                        <enabled>false</enabled> \
                        <mtu>1500</mtu> \
                        <address> \
                        <ip>172.0.0.1</ip> \
                        <prefix-length>29</prefix-length> \
                        </address> \
                    </ipv4> \
                </interface> \
                <interface> \
                    <name>eth1</name> \
                    <type>ianaift:softwareLoopback</type> \
                    <ipv4> \
                        <enabled>false</enabled> \
                        <mtu>1500</mtu> \
                        <address> \
                        <ip>10.0.0.1</ip> \
                        <prefix-length>29</prefix-length> \
                        </address> \
                    </ipv4> \
                </interface> \
            </interfaces>", YB_NONE, NULL, &xt, &xerr) < 0) {
        xml2txt_cb(stdout, xerr, cligen_output);
        goto done;
    }

    eth1 = xpath_first(xt, 0, "/interfaces/interface[name='eth1']", 0, 0);

    x1 = xpath_first(eth1, 0, "//ipv4/address/ip");
    assert(strcmp(xml_body(x1), "10.0.0.1") == 0);

    x2 = xpath_first(eth1, 0, "/interfaces/interface");
    assert(x2 == NULL);

    retval = 0;

done:
    return retval;
}
```
value x1 and x2 both check error.

**Comment by olofhagsand** [comment]
Its because the absolute paths "/" and "//" are defined in the API. 
When you assign `eth1`it is a pointer to within the tree `xt`.
When you use absolute paths you start from the top of the tree again, ie from xt.
Two ways to mitigate:
1. Use a relative path: `x1 = xpath_first(eth1, 0, ".//ipv4/address/ip")`
2. Make eth1 a tree of its own: `xml_rm(eth1); x1 = xpath_first(eth1, 0, "//ipv4/address/ip")`

**Comment by nowaits** [comment]
`eth1` is a tree node for `xt`, but when using `xpath_first`, `eth1` should be whole search tree and root of the search path.
Currently `xpath_first`'s behavor is very strange.

**Comment by olofhagsand** [comment]
It is how you define the document root / element in https://www.w3.org/TR/xpath-10/
In the clixon xpath API, the document root is defined as the top of the xml tree. The `xcur` argument of `xpath_first` and others is the "current" xml node (xcur) which can be any node in that tree, not necessarily the document root.
This is convenient if you want to use relative xpaths from any location in the tree (eg ../../foo/bar), which happens a lot in YANG.
It may be confusing if you expect xcur to be the root node.
It would be quite possible to create an alternative xpath_first function that assumes xcur to be the document root.
