### ISSUE TITLE
Need an option to disable restconf mandatory action of overwriting startup_db

### ISSUE THREAD

**Issue by nowaits** [clicon/clixon#230]
Hi olof,
      Currenly when restconf commit a change, the startup_db content also be changed, this behavior is very weird, though it's  mandatory in the RFC 8040 Sec 1.4. Is there possible add a restconf config or feature to disable this feature?

**Comment by olofhagsand** [comment]
Configure option `CLICON_RESTCONF_STARTUP_DONTUPDATE` added to disable RFC 8040 mandatory copy of running to startup after commit
