### ISSUE TITLE
Can startup mode to be extended to support running-startup mode?

### ISSUE THREAD

**Issue by nowaits** [clicon/clixon#234]
hi olof,
     In my project, when device initing, we create the startup_db file as init stage. After inited,  we can only change running db, and startup_db used for reseting device. After device inited by admin, we never change startup db and when need to reset device, we just delete or overwrite running db. Currently there are no startup_mode for my need. Can extend startup_mode to support it?

**Comment by olofhagsand** [comment]
Proposal is to add a new startup-mode Something like: "running-startup": first try running, if empty use startup instead.

**Comment by olofhagsand** [comment]
Please verify functionality
