### ISSUE TITLE
configure: error: CLIgen missing

### ISSUE THREAD

**Issue by lyzliyuzhi91** [clicon/clixon#246]
```
checking cligen/cligen.h usability... no                                             
checking cligen/cligen.h presence... no                                              
checking for cligen/cligen.h... no                                                   
configure: error: CLIgen missing. Try: git clone https://github.com/clicon/cligen.git
```

I get the code via downloading the zip because I cannot use git in my linux machine.
So how can i successfully build without using git clone ?
thanks.

**Comment by olofhagsand** [comment]
You need to download, configure and install cligen first, just as you started with clixon. There is a zip file for cligen as well, at https://github.com/clicon/cligen.

**Comment by lyzliyuzhi91** [comment]
My negligence. I misread the cligen.git as clixon.git.
thanks.
