### ISSUE TITLE
Unable to connect to clixon_backend

### ISSUE THREAD

**Issue by mgupta1308** [clicon/clixon#25]
I have compiled cligen and clixon and configured to install in my home directory. I have successfully compiled and installed "example" as well. The compilation and install was successful, however when I try to connect to clixon_backend I get an error example.sock not found. I do not see it getting generated in var/example/ folder as well. Is the file packaged in clixon or auto generated?

**Comment by ngashok** [comment]
u might have missed the step of creating the user group...its in FAQ.

The config demon requires a valid group to create a server UNIX socket. Define a valid CLICON_SOCK_GROUP in the config file or via the -g option or create the group and add the user to it. The default group is 'clicon'. On linux: sudo groupadd clicon. sudo usermod -a -G clicon user.

**Comment by mgupta1308** [comment]
I do not have sudo permissions on the machine. The reason I installed the package in my home directory. Is there a workaround for that?

**Comment by olofhagsand** [comment]
Yes, 
1) You install the package in your homedir (you already did that)
2) You edit the config file (eg example.xml) to point to files and resources in your homedir. You may want to look in yang/clixon-config@2018-04-30.yang for all options. Specifically:
- Set CLICON_SOCK_GROUP to a unix group you have w access to
- CLICON_BACKEND_PIDFILE
- CLICON_SOCK
- CLICON_*_DIR
Please tell if this works and I can add a FAQ entry
3)  CLICON_SOCK_GROUP

**Comment by olofhagsand** [comment]
I think this is resolved?
