### ISSUE TITLE
Request: XML Parser should support CDATA

### ISSUE THREAD

**Issue by dcornejo** [clicon/clixon#26]
There were some changes recently to protect data being passed through clixon from being misinterpreted as XML and breaking the parser (thanks for that).

We are still having problems because you need to keep track of whether a string has been encoded or decoded already - for example if I start with the string "%" and using URI encoding the encoded result is "%25" if that gets encoded again, I get "%2525" and when I'm decoding I have no way to tell whether the original was "%25" or "%"... (the same thing can happen with XML encoding too)

We believe that the best way to deal with this is to use CDATA - which essentially "quotes" the data and tells the parser to skip on to the end marker. There's no laborious or inefficient en/decoding and we can pass it through as many time as we like and it's not altered.

So, we're requesting you implement CDATA in clixon,

thanks

**Comment by olofhagsand** [comment]
Fixed in https://github.com/clicon/clixon/commit/8b31d838064cc37c0840fd49bfb180e1a552f14a#diff-4ac32a78649ca5bdd8e0ba38b7006a1e
