### ISSUE TITLE
Netconf With-defaults Capability

### ISSUE THREAD

**Issue by pheller** [clicon/clixon#262]
It is desirable to support https://datatracker.ietf.org/doc/html/rfc6243 such that elements within a configuration datastore can be identified as default or non-default without the need for schema awareness.  For example:

```
    <config xmlns:nc2="urn:ietf:params:xml:ns:netconf:default:1.0" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
      <sys:system xmlns:sys="urn:ietf:params:xml:ns:yang:ietf-system">
        <sys:ntp>
          <sys:enabled nc2:default="true">true</sys:enabled>
        </sys:ntp>
      </sys:system>
    </config>
```

With this supported, subsequent features can be supported, like `show configuration | display defaults`, and thus `show configuration` could omit defaults for a more terse display.

**Comment by olofhagsand** [comment]
feature implemented and merged: https://github.com/clicon/clixon/commit/e39d18d59fb61f39f005f51f5ba9f8e3b575bc2a

**Comment by pheller** [comment]
Tested both NETCONF and RESTCONF - looks good to me, thanks!
