### ISSUE TITLE
Performance issue when parsing large JSON param

### ISSUE THREAD

**Issue by zaker139** [clicon/clixon#266]
https://github.com/clicon/clixon/blob/3cd3f7987d8042b3211b5e503362bee6fd7a2e8f/lib/src/clixon_json_parse.y#L301

JSON parsing became quite slow, when request body contains a large size string. Since 'strlen' invokes every char for each.

`	  int len = strlen($1);`
`         $$ = realloc($1, len+strlen($2) + 1);` 
`	  sprintf($$+len, "%s", $2); `

'$1' orginal string may be damn large. eg. When post a large json param size exceed 10M by restconf protocol,  then the process was stuck there.

**Comment by olofhagsand** [comment]
Thanks for detecting, please verify
