### ISSUE TITLE
Writing list data entries leads to internal error

### ISSUE THREAD

**Issue by dus7eh** [clicon/clixon#268]
Having yang container with a list object data can be set with curl `PUT` request passing the following sample payload:

```
{
  "mac:my-ni": {
    "if": [{
      "cl-port:my-port": [{
        "port-number": 0,
        "admin-state": "up"
      }, {
        "port-number": 1,
        "admin-state": "up"
      }]
    }]
  }
}
```
where `if` is a container and `my-port` is a list.

Such a request returns `201` status code which is expected.
However, any subsequent `GET` queries to read the data ends retrieving payload with the following error message:
```
{
  "rpc-error": {
    "error-type": "application",
    "error-tag": "operation-failed",
    "error-info": {
      "bad-element": "my-port"
    },
    "error-severity": "error",
    "error-message": "Namespace mismatch. Internal error, backend returned invalid XML."
  }
}

```

Looking into `running_db` I can see more or less the following structure:

```
<config>
   <my-ni xmlns="urn:cl:params:xml:ns:yang:mac">
      <if>
         <cl-if-ports:my-port xmlns:cl-if-ports="urn:cl:params:xml:ns:yang:cl-port">
            <cl-if-ports:port-number>0</cl-if-ports:port-number>
            <cl-if-ports:admin-state>UP</cl-if-ports:admin-state>
         </cl-if-ports:my-port>
         <my-port>
            <port-number>1</port-number>
            <admin-state>UP</admin-state>
         </my-port>
      </if>
   </my-ni>
   ... # not important stuff
</config>
```

Some namespaces seem to be missing for the second `my-port` entry which may lead to the corrupted xml message.
This makes further use of the server impossible.

**Comment by olofhagsand** [comment]
Can you please provide the YANG for the XML ^?

**Comment by olofhagsand** [comment]
Fixed by PR

**Comment by dus7eh** [comment]
I've prepared a separate test case on my internal fork to verify this (two yang models with augmentation). I can post it as a separate PR. Not sure how it fits the current tests and the way they are organized but we can discuss this later.

**Comment by olofhagsand** [comment]
Well, in this case you fixed it and I verified your fix, so I guess I can close it.
