### ISSUE TITLE
OpenConfig Path Compression Support

### ISSUE THREAD

**Issue by wyltk-pfleming** [clicon/clixon#274]
Requesting support for path compression as documented [here](https://github.com/openconfig/ygot/blob/master/docs/design.md#openconfig-path-compression)

OpenConfig path are repetitive for human CLI consumption due to levels of hierarchy being introduced to the model.

Inefficient behavior:
* Data values (leaf nodes) are mirrored in a config and state container
* YANG list nodes are enclosed in a container, which they are the sole child of. 

Utilizing the above referenced method 
`/interfaces/interface/subinterfaces/subinterface/ipv4/addresses/address becomes /interface/subinterface/ipv4/address.
/interfaces/interface/subinterfaces/subinterface/config/enabled becomes /interface/subinterface/enabled.
/interfaces/interface/subinterfaces/subinterface/state/oper-status becomes /interface/subinterface/oper-status.`

I believe this should only apply at the CLI layer to allow compatibility with existing tools that expect OpenConfig paths.

**Comment by olofhagsand** [comment]
using `CLICON_CLI_GENMODEL=HIDE` already takes care of the second requirement

**Comment by olofhagsand** [comment]
Complete closing
