### ISSUE TITLE
type leafref in type union ineffective

### ISSUE THREAD

**Issue by swh1991** [clicon/clixon#277]
yang defintion:

        leaf test_name1 {
            type string;
        }
        leaf test_name2 {
            type string;
        }
        leaf test_name_ref {
            type union {
                type leafref {
                    path "../test_name1";
                    require-instance true;
                }
                type leafref {
                    path "../test_name2";
                     require-instance true;
                }
            }
        }

startup_db as bellow and run ok,  but expect run  error.

     <configuration>
           <test_name1>test1</test_name1>
           <test_name2>test2</test_name2>
           <test_name_ref>test3</test_name_ref>  ----> not a leafref test_name1 or test_name2
     </configuration>

**Comment by olofhagsand** [comment]
Confirmed, can recreate

**Comment by olofhagsand** [comment]
The nature if this is issue is that validation of leafref's and identityref's in union doe does not work.

**Comment by olofhagsand** [comment]
Fixed by patch. 
new test in test_leafref_union.sh for both leafref and identityref in union.
Please check and close if verified.
