### ISSUE TITLE
'when' condition violation with namespace-qualified OpenConfig network-instance protocol identifiers

### ISSUE THREAD

**Issue by pheller** [clicon/clixon#278]
When creating an OpenConfig network-instance and using the OpenConfig namespace-qualified protocol identifiers, a when condition appears to be violoated:

Examples:
```
vagrant@ubuntu1804.localdomain / # set network-instances network-instance default protocols protocol oc-pol-types:BGP testing config identifier oc-pol-types:BGP
vagrant@ubuntu1804.localdomain / # set network-instances network-instance default protocols protocol oc-pol-types:BGP testing config name foo
vagrant@ubuntu1804.localdomain / # set network-instances network-instance default protocols protocol oc-pol-types:BGP testing bgp global config router-id 1.2.3.4 
Oct 19 13:47:27: Editing configuration: application unknown-element Node 'bgp' tagged with 'when' condition './config/identifier = 'BGP'' in module 'openconfig-network-instance' evaluates to false in edit-config operation (see RFC 7950 Sec 8.3.2) <bad-element>bgp</bad-element> 
```

```
vagrant@ubuntu1804.localdomain / # set network-instances network-instance default protocols protocol oc-pol-types:LOCAL_AGGREGATE AGGREGATE_v4 config identifier oc-pol-types:LOCAL_AGGR$
vagrant@ubuntu1804.localdomain / # set network-instances network-instance default protocols protocol oc-pol-types:LOCAL_AGGREGATE AGGREGATE_v4 config name AGGREGATE_v4
vagrant@ubuntu1804.localdomain / # set network-instances network-instance default protocols protocol oc-pol-types:LOCAL_AGGREGATE AGGREGATE_v4 local-aggregates aggregate 1.2.3.0/24 c$
Oct 19 14:20:52: Editing configuration: application unknown-element Node 'local-aggregates' tagged with 'when' condition './config/identifier = 'LOCAL_AGGREGATE'' in module 'openconfig-network-instance' evaluates to false in edit-config operation (see RFC 7950 Sec 8.3.2) <bad-element>local-aggregates</bad-element>
CLI command error
```

The workaround is to explicitly provide the local-name only as the protocol-identifier; e.g., `BGP` rather than value offered with tab completion: `oc-pol-types:BGP`.

**Comment by pheller** [comment]
I was incorrect, the workaround is invalid as it causes violation of another schema constraint:

`vagrant@ubuntu1804.localdomain / # validate
Nov  2 19:40:46: Validate failed. Edit and try again or discard changes: application operation-failed Identityref validation failed, BGP not derived from INSTALL_PROTOCOL_TYPE in openconfig-policy-types.yang:160
CLI command error`

**Comment by pheller** [comment]
Actually, the workaround is invalid.  It causes a constraint violation elsewhere in the schema.  As such, this is a show-stopper for us.

```
vagrant@ubuntu1804.localdomain / # validate
Nov  2 19:40:46: Validate failed. Edit and try again or discard changes: application operation-failed Identityref validation failed, BGP not derived from INSTALL_PROTOCOL_TYPE in openconfig-policy-types.yang:160
CLI command error
```

**Comment by olofhagsand** [comment]
Actually this seems to be a problem with the openconfig spec, not Clixon. See eg the following openconfig known issue:
https://github.com/openconfig/public/issues/478
My recommendation would be to patch the openconfig spec until they patch it

**Comment by pheller** [comment]
Yes, I'll do just that, and close out the issue once I confirm all looks good here.  Apologies for not more fully investigating the schema first.

**Comment by pheller** [comment]
Verified, applying the changes in the referenced PR to OpenConfig does indeed resolve this problem (yet raises others, in openconfig).

Apologies for the misdirection.
