### ISSUE TITLE
Recursive search CLIXON_YANG_DIR

### ISSUE THREAD

**Issue by pheller** [clicon/clixon#284]
It would be convenient if Clixon recursively searched each specified CLIXON_YANG_DIR for required yang modules.  The particular use case would be for OpenConfig which has a relatively broad directory hierarchy.

Not a problem to combine them in a single directory, or enumerate the list of directories with multiple instances of CLIXON_YANG_DIR, just would be more concise to use the directory as cloned from upstream and only add one configuration line to search it.

**Comment by olofhagsand** [comment]
This should work now @pheller, please verify it works as intended.

**Comment by pheller** [comment]
Looks good, thanks.
