### ISSUE TITLE
JSON leaf-list output single element leaf-list does not use array 

### ISSUE THREAD

**Issue by swh1991** [clicon/clixon#289]
Be similar Bug 261, use release version 5.3 , issue persist , different use and result is different.

Example YANG, result is ok.

container test {
    leaf-list number{
        type int32;
   }
}
Expected output:
{"test": {"number": [1]}
Actual output:
{"test": {"number": [1]}
Example YANG, result is error.

leaf-list number{
    type int32;
}
Expected output:
{"number": [1]}
Actual output:
{"number": 1}​

**Comment by olofhagsand** [comment]
Please verify
