### ISSUE TITLE
lock/unlock behavior in example cli with datastore nocache mode

### ISSUE THREAD

**Issue by jaeho9929** [clicon/clixon#300]
When I enabled nocache option in clixon configuration file, clixon backend returns unlock failed returns.
Is this intended behavior?
In default mode, it returns rpc ok.

1. Added one line in ~/clixon/example/main/example.xml
```
<CLICON_DATASTORE_CACHE>nocache</CLICON_DATASTORE_CACHE>
```

2. Run backend and cli
```
clixon_backend -F -f /usr/local/etc/example.xml -D 1
clixon_cli -f /usr/local/etc/example.xml
```

3. In cli console
```
user> lock
user> set table parameter aaaa value 1111
user> unlock
Feb  8 06:36:56: Configuration unlock: protocol lock-denied Unlock failed, lock is not currently active <session-id>0</session-id>
CLI command error
user> 
```

**Comment by olofhagsand** [comment]
Different settings of datastore cache is unfortunately not currently part of the regression test matrix.
Thanks for reporting

**Comment by olofhagsand** [comment]
Nocache is now obsoleted
