### ISSUE TITLE
Enhancement request of RFC 8525

### ISSUE THREAD

**Issue by dima1308** [clicon/clixon#304]
We are using CLIXON ver 5.5 
I enabled the yang library support by changing the CLIXON configuration file core.xml as described below:
```
<clixon-config xmlns="http://clicon.org/config">
---snip---
  <CLICON_MODULE_LIBRARY_RFC7895>true</CLICON_MODULE_LIBRARY_RFC7895>
---snip---
</clixon-config>
```
I tried to read yang library content using the MGSoft Netconf browser.
Please see the RPC exchange below:

```
Wed Feb 16 16:49:20 IST 2022
c4694751-32ec-4ec2-b764-1c65db789a64 RPC sent
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="2">  <get>
    <filter>
      <yanglib:yang-library xmlns:yanglib="urn:ietf:params:xml:ns:yang:ietf-yang-library">
      </yanglib:yang-library>
    </filter>
  </get>
</rpc>


Wed Feb 16 16:49:20 IST 2022
c4694751-32ec-4ec2-b764-1c65db789a64 RPC received
<?xml version="1.0" encoding="utf-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="2">
    <data/>
</rpc-reply>
```

I expect to see the list of supported yang libraries in the reply. But actually, the reply list is empty.
Note: the get request is automatically generated by the MGSoft Netconf browser - this is not what I manually entered.

Related bug: https://github.com/clicon/clixon/issues/273

**Comment by olofhagsand** [comment]
Actually this is RFC 8525 and Clixon currently supports only RFC 7895, as documented here: https://clixon-docs.readthedocs.io/en/latest/standards.html
Can you please re-title this to a enhancement request of RFC 8525?

**Comment by dima1308** [comment]
@olofhagsand done

**Comment by olofhagsand** [comment]
RFC8525 support in
https://github.com/clicon/clixon/commit/dd2ac56af89161233780a4a2f1f2547544a3feb7
Please verify
