### ISSUE TITLE
Restconf PATCH method request failed on item defined by submodule

### ISSUE THREAD

**Issue by zaker139** [clicon/clixon#306]
Consider YANG models below:
test.yang
```
module test {
    yang-version 1.1;
    namespace "http://www.test.com/test";
    prefix test;

    include test-augment;

    container con {
        leaf a {
            type string;
        }
    }    
}
```

test-augment.yang
```
submodule test-augment {

    belongs-to "test" {
        prefix "test";
    }

    augment "/test:con" {
        leaf b {
            type string;
        }
    }
}
```

Using restconf PATCH **/test:con/a** success.
```
curl -X PATCH -H "Content-Type: application/yang-data+json" -d '{
    "test:a": "hello123"
}' http://localhost/restconf/data/test:con/a
```
Whereas same request on **/test:con/b** would failed with error below:
```
curl -X PATCH -H "Content-Type: application/yang-data+json" -d '{
    "test:b": "hello13434"
}' http://localhost/restconf/data/test:con/b
{
"ietf-restconf:errors" : {
  "error": {
    "error-type": "rpc",
    "error-tag": "malformed-message",
    "error-severity": "error",
    "error-message": "Data is not prefixed with matching namespace"
  }
}

}
```

Seems in  **restconf_methods.c:372**,  _ymoddata_ and _ymodapi_  are not the samething.

https://github.com/clicon/clixon/blob/31719b5ef4e60aaa5d881de8c69c3004562a3164/apps/restconf/restconf_methods.c#L372

_ymodapi_ points to a submodule yang_stmt, but _ymoddata_ points to a main module.

**Comment by olofhagsand** [comment]
This is probably an effect of fix of https://github.com/clicon/clixon/issues/303

**Comment by olofhagsand** [comment]
Thanks for detecting this important cornercase error.
Please verify the submitted fix.
