### ISSUE TITLE
RPC operation should use module name rather than prefix

### ISSUE THREAD

**Issue by dcornejo** [clicon/clixon#31]
see @dmittryvvv comment on closed https://github.com/clicon/clixon/issues/30

RFC-8040 states the proper specification for an operation is

`POST /restconf/operations/<module_name>:<rpc_procedure> HTTP/1.1
`

but clixon requires

`POST /restconf/operations/<module_prefix>:<rpc_procedure> HTTP/1.1
`

**Comment by olofhagsand** [comment]
I needed to make a larger and more specific change for restconf operations GET and PUT, see patch above. 
Thanks for detecting this major divergence from RFC 8040!
