### ISSUE TITLE
Xpath API do not support filter data by wildcard

### ISSUE THREAD

**Issue by zaker139** [clicon/clixon#313]
xml content:
```xml
<root>
    <a>123</a>
    <b>456</b>
    <c>789</c>
</root>
```

Xpath  like "/root/*[.='789']" shoud return **\<c\>789\</c\>**

Seems xpath API like **xpath_first** now do not support path like above.

**Comment by olofhagsand** [comment]
Should be fix by patch above. Please verify.

**Comment by olofhagsand** [comment]
Now fixed. Please verify

**Comment by zaker139** [comment]
Fixed
