### ISSUE TITLE
autocli/exclude logic not implemented

### ISSUE THREAD

**Issue by zaker139** [clicon/clixon#316]
https://github.com/clicon/clixon/blob/cee735e586b8899bbce0203ee782fa08a8600e63/yang/clixon/clixon-config%402022-02-11.yang#L76

Exclude is not defined in clixon-autocli.yang.

**Comment by olofhagsand** [comment]
This API is changed to a more flexible exclude logic as described here:
https://clixon-docs.readthedocs.io/en/latest/cli.html#upgrade-from-pre-clixon-5-5
and specifically for exclude here:
https://clixon-docs.readthedocs.io/en/latest/cli.html#module-enable-rules

**Comment by zaker139** [comment]
It's a little awesome, when most of modules should be included, but one should be excluded. I must list all modules in 'enable rules'.
