### ISSUE TITLE
prevent  clixon-restconf@2021-05-20.yang module from loading

### ISSUE THREAD

**Issue by eduardpo** [clicon/clixon#318]
Hi @olofhagsand,

We are trying to prevent clixon-restconf module from loading by clixon at all,
Which will presumably allow us to completely  hide restconf/netconf access of **restconf configuration** from user,
In this regard i would like to ask you few questions if I may:

1. does the effort make sense and what could be the impact on the restconf/netconf system?
2. what's the prefered way to accomplish the goal?

Please advise,
Ed

**Comment by olofhagsand** [comment]
Should work by just:
```
./configure --without-restconf
```
See also https://clixon-docs.readthedocs.io/en/latest/restconf.html#installation
If that does not work it is an error.

**Comment by eduardpo** [comment]
Hi @olofhagsand,

Thanks for reply,
According to the manual `./configure --without-restconf` means - # Do not build restconf,
Which is not that we want to achieve, we do use restconf protocol in our setup.
As I understand, **clixon-restconf@2021-05-20.yang** module is responsible for configuration of restconf daemon/protocol functionality?
Does it make sense not to load this particular module and continue to fully use restconf functionality?


Thanks,
Ed

**Comment by olofhagsand** [comment]
I understand, makes sense. 
Is it only in the CLI or do you want to hide it also from netconf/restconf for configuration?

**Comment by olofhagsand** [comment]
Changing it to a change request: make it optional to load clixon-restconf.yang

**Comment by eduardpo** [comment]
> I understand, makes sense. Is it only in the CLI or do you want to hide it also from netconf/restconf for configuration?

We want to hide it from all frontend's - cli, netconf, restconf...
