### ISSUE TITLE
provide support for load config of cli format along with json and xml format as save config is supported for all 3 formats 

### ISSUE THREAD

**Issue by DeekshaBhandary** [clicon/clixon#320]

**Comment by olofhagsand** [comment]
Added, please verify

**Comment by pheller** [comment]
I've just tested the load replace method for cli and while it does work, sizable configurations take quite some time to load.

As an example, I have a ~ 6200 line configuration file (using OpenConfig network-instances, interfaces, system schemas) that takes  ~ 9 minutes to complete, and during which clixon_backend consumes the majority of the CPU.

```
13990 root      20   0  145244  52796   4020 R  94.0  2.6   4:32.22 clixon_backend
```

**Comment by olofhagsand** [comment]
I take this as a verification of the function and therefore close this.
Regarding the performance 6200 line / 9 minutes, can you please open a separate (non-functional) issue on that?
