### ISSUE TITLE
Error message seen twice in some cases

### ISSUE THREAD

**Issue by DeekshaBhandary** [clicon/clixon#325]
```
supervisor@element1: cfg> load config invaidfile.json
Apr 14 09:10:57: load_config_file: 1536: UNIX error: load_config: stat(invaidfile.json): No such file or directory
UNIX error: load_config: stat(invaidfile.json): No such file or directory
supervisor@element1: cfg>
```

**Comment by olofhagsand** [comment]
The reason this is so is that loggin is directed to stderr AND there is an CLI command error message on stderr.
One workaround is to direct logging somewhere else with -l command-line. For example clixon_cli -l s to direct logging to syslog. This may not be a practical but illustrates what is going on.
As part of the patch I also added `-l n` as a way to shhut off logging completely. However, there may be other logging other than errors, such as warnings that may be useful to have.
A committed patch is to NOT print a CLI command error to stderr if logging is already directed to stderr.
However, if logging is directed elsewhere, then the CLI command error is printed on stderr.
I hope this solves this issue.
Please review.
