### ISSUE TITLE
Returning a string  while Querying leaf-list for single entry

### ISSUE THREAD

**Issue by wasimRonaldoE7** [clicon/clixon#326]
YANG STRUCTURE
        leaf-list service-group {
            type leafref {
                path "/path";
            }
        }
ISSUE:
            After creating a service-group of length 1 , it is returning as string instead of array while querying

On Create Operation
          "service-group":["service_first"] ,

On GET Operation
          "service-group": "service_first",

**Comment by wasimRonaldoE7** [comment]
For length more than 1 , it's working fine

**Comment by olofhagsand** [comment]
Seems only to apply to top-level leaf-list:s. That is, if you have a container around the leaf-list the error does not occur. 
```
container c{
  leaf-list service-group {
    type leafref {
      path "/path";
    }
  }
}
```
Still an error that must be fixed, but could work as a temporary workaround.

**Comment by olofhagsand** [comment]
Fixed by patch. Please verify and closed if fixed.
