### ISSUE TITLE
Feature Request: Log SSL events

### ISSUE THREAD

**Issue by dcornejo** [clicon/clixon#331]
For security audit we should log all connections to the HTTP server.

SSL failures should be logged at a higher severity level (maybe Error) so that they can be filtered from successes (Info or Notice?).

**Comment by olofhagsand** [comment]
Can you please provide examples?
Potential candidates are 
1) in read_ssl():;
 clicon_log(LOG_WARNING, "%s SSL_read(): %s", __FUNCTION__, strerror(errno));
2) in errors from SSL_write in  native_buf_write()
 etc.

**Comment by olofhagsand** [comment]
Added syslog on NOTICE level for failed cert verification.
Example:
```
Jun  8 13:11:11 Alarik clixon_restconf[17371]: Cert error: /CN=limited/emailAddress=limited@foo.bar/O=Clixon/L=Stockholm/C=SE: certificate has expired
```
