### ISSUE TITLE
Support for RFC 8528 - YANG Schema Mount

### ISSUE THREAD

**Issue by pheller** [clicon/clixon#333]
There are several use cases where it would be helpful to attach the entirety of one schema to a mount point in another.   There is more detail on the challenge and solution in [RFC 8528](https://datatracker.ietf.org/doc/html/rfc8528).

One example use case would be the logical partitioning of a single device.  Consider a router that can be logically subdivided, where each partition maintains a complete isolated configuration.  In this use case, you might have a schema excerpt as follows, where the entire legal schema is attached to the `partition-config` mount-point. 

```
container device {
  list partition {
    key name;
    leaf name {
      type string;
    }
    container config {
      yangmnt:mount-point "partition-config";
    }
  }
}
```

**Comment by olofhagsand** [comment]
This has been in clixon since 6.1 and is a basis for the controller work
