### ISSUE TITLE
Error parsing clixon-config.yang

### ISSUE THREAD

**Issue by magicalfox007** [clicon/clixon#335]
Anybody met this error when starting clixon_backend ？

> 
> Dec 20 13:20:02: clixon_yang_parseerror: 344: Yang error: /usr/share/clixon/yang/clixon-config@2019-09-11.yang on line 1: syntax error at or before: ''
> Dec 20 13:20:02: Yang error: /usr/share/clixon/yang/clixon-config@2019-09-11.yang on line 1

developing based on clixon-4.2.0

**Comment by olofhagsand** [comment]
I never seen that for a YANG file, that parser is fairly static.
Also, seems like a very old version. could be
 a version mis-match of some sort.
Line 1 in a (formatted) yang file is also very early, usually just "module clixon-config{\n".
One far-fetched explanation would be some escape character in the file, or possible mis-handling of \r from DOS newline formatting.

**Comment by magicalfox007** [comment]
This error may have more to do with the bison/flex version being too old，I am trying to modify my makefile to recompile.

**Comment by olofhagsand** [comment]
Does this mean this error only occurs in 4.2.0 and has been fixed in later versions, and there is a workaround by the type change patch?
If so, can you please close this issue.

**Comment by magicalfox007** [comment]
This error only occurs in 4.2.0 or other versions which include "int c" statement in function "yang_parse_file". (e.g. 4.3.0 still exists)
It has been fixed in latest version.
