### ISSUE TITLE
Can't create IF-MIB ofStackEntry

### ISSUE THREAD

**Issue by shmuelhazan** [clicon/clixon#339]
Branch name: https://github.com/clicon/clixon/commit/a61567a916da2c58cc16a4d161238b8a7b1d9e3e

1. I have added  IF-MIB.yang from https://github.com/clicon/mib-yangs/blob/main/IF-MIB.yang to the config xml by specifying `  <CLICON_SNMP_MIB>IF-MIB</CLICON_SNMP_MIB>`. 
2. I removed the `config false` from the yang in order to be able to see it in CLI and DB. 
3. When configuring inside of the CLI, I was able to see the values in snmpd:
```
clixon> set IF-MIB ifStackTable ifStackEntry 9 9
clixon> q
# snmpwalk -v 2c -c public 127.0.0.1 .1.3.6.1.2.1.31.1.2.1
IF-MIB::ifStackHigherLayer.9.9 = INTEGER: 9
IF-MIB::ifStackLowerLayer.9.9 = INTEGER: 9
```
However, when I tried to configure a new row from snmp, I was not able to see it in clixon:
```
root@terragraph:~# snmpset -c public -v 2c 127.0.0.1 .1.3.6.1.2.1.31.1.2.1.3.5.9
 = 4
IF-MIB::ifStackStatus.5.9 = INTEGER: createAndGo(4)
clixon>show IF-MIB ifStackTable
ifStackTable {
    ifStackEntry {
        ifStackHigherLayer 9;
        ifStackLowerLayer 9;
    }
}
```
(I expected to see another entry with values 5,9)

**Comment by olofhagsand** [comment]
This also seems to work:
```
sh> /usr/local/bin/snmpset -On -c public -v2c localhost  .1.3.6.1.2.1.31.1.2.1.3.7.7 i 5
.1.3.6.1.2.1.31.1.2.1.3.7.7 = INTEGER: createAndWait(5)
cli> show auto IF-MIB ifStackTable 
<ifStackTable>
   <ifStackEntry>
      <ifStackHigherLayer>5</ifStackHigherLayer>
      <ifStackLowerLayer>9</ifStackLowerLayer>
      <ifStackStatus>createAndGo</ifStackStatus>
   </ifStackEntry>
</ifStackTable>

```

**Comment by shmuelhazan** [comment]
Looks good now. Thanks.
