### ISSUE TITLE
"autocli:hide-show" extension cause bug in xmldb_put method

### ISSUE THREAD

**Issue by vvsosed** [clicon/clixon#343]
Hi 
I've used the snmp branch and encountered a possible bug when I tried to use *int xmldb_put(...)* API call.
Some of the used YANG models contain *autocli:hide-show* extension. I've found that when we try to store data with *xmldb_put(...)* call the created database file doesn't contain data that was declared as *autocli:hide-show* in YANG model.
Probably, the root of this issue in [xml2file_recurse(...)](https://github.com/clicon/clixon/blob/4f9ed02a46d4422eab742793045d274b264c45b9/lib/src/clixon_xml_io.c#L120) implementation. The call sequence is *int xmldb_put(...) -> clixon_xml2file(...) -> xml2file_recurse(...).*

**Comment by olofhagsand** [comment]
I need some more context.
Can you describe a specific context (ie testcase) when this appears and symptoms.
Eg, xml config file, cli/restconf/netconf call that causes the error, and what happens when the error occurs.

**Comment by olofhagsand** [comment]
A previous rewrite of xml/json/text function (in June) made CLI hide commands effective also in backend which had datastore side-effects.
Now fixed, but note changed API of:
- clixon_xml2file()
- clixon_json2file()
- clixon_json2cbuf()
- clixon_txt2file()
Please verify fix
