### ISSUE TITLE
All values in list don't appear when writing "show <list>" in cli

### ISSUE THREAD

**Issue by shmuelnatan** [clicon/clixon#359]
Let's say we have the following yang
```
container foo-con {
    list foo-list {
        key "name";
        leaf name {
           type string;
       }
    }
}
```
Now let's set two values
```
cli>set foo-con foo-list boo1
cli>set foo-con foo-list boo2
cli>commit
```
Now requesting to show the container will show the following
```
cli>show foo-con
foo-con {
   foo-list boo1{}
   foo-list boo2{}
}
```
but showing the list will only show the first value
```
cli>show foo-con foo-list
foo-list boo1{}
 
```
This is a regression since previously (prior to release 5.8.0) showing the list would show all the values in the list.

**Comment by shmuelnatan** [comment]
@olofhagsand Does this bug happen in your code?

**Comment by olofhagsand** [comment]
Sorry, havent had time to look. 
Now I see it does also appear in my code.
A few reflections:
1) If it is in fact a regression I will investigate why this happens.
2) The Yang rfc:s (eg rfc8040) primarily focus on "objects/resources", where a container, leaf and a list element is such a resource, whereas  a whole list is not. I think it is valuable to see the whole list and therefore label this as a bug.
3) This is a behavior of `cli_show_auto()` ie not really related to netconf/yang itself.

**Comment by olofhagsand** [comment]
Yes, I see this is a regression, since it worked in 5.7.0, but not in 5.8.0
