### ISSUE TITLE
SNMP "smiv2" yang extension doesn't work on augmented nodes

### ISSUE THREAD

**Issue by vvsosed** [clicon/clixon#366]
I use [IF-MIB.yang](https://github.com/YangModels/yang/blob/main/vendor/cisco/xe/1651/MIBS/IF-MIB.yang) in order to add support for SNMP ifTable. All nodes inside IF-MIB.yang are already properly tagged with smiv2:oid, smiv2:max-access yang extension tags.
SNMP [ifTable container](https://github.com/YangModels/yang/blob/5c289956f96fb2e4b1969c0da0bf21884c40a6eb/vendor/cisco/xe/1651/MIBS/IF-MIB.yang#L165) (in IF-MIB.yang) contains [ifSpeed leaf](https://github.com/YangModels/yang/blob/5c289956f96fb2e4b1969c0da0bf21884c40a6eb/vendor/cisco/xe/1651/MIBS/IF-MIB.yang#L227) which holds current bandwidth in bits per second. Also, [ifHighSpeed leaf](https://github.com/YangModels/yang/blob/5c289956f96fb2e4b1969c0da0bf21884c40a6eb/vendor/cisco/xe/1651/MIBS/IF-MIB.yang#L970) is added as yang extension to hold bandwidth bigger than 4,294,967,295 bit/sec. So in my case, I filled both nodes [as stated in the description](https://github.com/YangModels/yang/blob/5c289956f96fb2e4b1969c0da0bf21884c40a6eb/vendor/cisco/xe/1651/MIBS/IF-MIB.yang#L233) and checked that they (base ifSpeed and augmented ifHighSpeed) held proper values through NETCONF. After, I tried to get the values with help of SNMP by using snmpwalk CLI tool. Unfortunately, snmpwalk's output consisted of values from the base ifTable container (i.e. ifSpeed) and none of the augmented nodes (i.e. mentioned earlier ifHighSpeed augmented node).

This issue was reproduced at latest clixon master revision 5f38b50eabd76140d69e464eb2695ed3c937e8cd.

**Comment by olofhagsand** [comment]
Fixed snmp-get for augmented tables. 
May remain work for getnext/walk

**Comment by olofhagsand** [comment]
getnext + walk should also work, and regression tests added.
Please verify

**Comment by vvsosed** [comment]
Thanks a lot! We will check it soon.
