### ISSUE TITLE
unneeded trailing zero character on SNMP strings

### ISSUE THREAD

**Issue by dima1308** [clicon/clixon#367]
Please see attached screenshot
On each SNMP string on responce, there is an extra trailing zero character 
Can you please check it?
![Screenshot from 2022-09-20 19-10-20](https://user-images.githubusercontent.com/7607499/191508982-49f74343-f91b-4d8b-9124-f1a1e9a0945f.png)

**Comment by olofhagsand** [comment]
This seems to be (from SNMPv2-MIB.yang):
```
     leaf sysDescr {
        type snmpv2-tc:DisplayString {
          length "0..255";
        }
       ...
        smiv2:oid "1.3.6.1.2.1.1.1";
      }
```
The type resolves to:
```
  typedef DisplayString {
    type string {
      length "0..255";
    }
    ...
     smiv2:display-hint "255a";
```
It seems that display-hint 255a is not handled correctly by Clixon (display-hint 255t is handled correctly).
A proposal is to treat 255a in the same way as 255t changing the string to an ASN.1 fixed string.

**Comment by olofhagsand** [comment]
Patch submitted. Please verify.
