### ISSUE TITLE
message-id present on netconf app "hello"

### ISSUE THREAD

**Issue by pheller** [clicon/clixon#369]
Per RFC 6241 Appendix B, XML Schema, the `message-id` attribute is legal on `rpc` and `rpc-reply` elements, but it is present on  the `hello` element sent by clixon_netconf application.

Strictly validating clients may refuse to communicate with Clixon when this attribute is present.

**Comment by olofhagsand** [comment]
Fixed: please verify

**Comment by pheller** [comment]
Works as intended, thanks!
