### ISSUE TITLE
Restconf not starting....

### ISSUE THREAD

**Issue by shubhtrix** [clicon/clixon#37]
Hi @olofhagsand 

I have been using restconf for past some time. Then, I recompiled the apps folder and after that it stopped working. 
**I am using develop branch**
**ERROR IS**

`root@SHUBH:/home/shubham/RESTCONF_DEVELOP/clixon/example#  sudo su -c "/www-data/clixon_restconf -f /usr/local/etc/example.xml " -s /bin/sh www-data
bind/listen: Address already in use`
**ADDRESS ALREADY IN USE**

**I ALSO CHECKED FOR**
'root@SHUBH:/home/shubham/RESTCONF_DEVELOP/clixon/example# grep clicon /etc/group
clicon:x:1002:root,www-data
root@SHUBH:/home/shubham/RESTCONF_DEVELOP/clixon/example# '

**PLEASE HELP**

**Comment by shubhtrix** [comment]
Got it working now, by permitting the directory www-data under root for all users.
Thanks :+1:

**Comment by olofhagsand** [comment]
Actually, /www-data should probably have permissions something like:
drwxr-xr-x   2 www-data www-data  4096 Jul 25 11:01 www-data
Allowing all users write access may be too loose.
Now I am unsure exactly where this should be done in the installprocess, I thought this was added by nginx or apache, but I see I have to do this manually sometimes. Maybe should verify this in the restconf install.

**Comment by olofhagsand** [comment]
Fixed by https://github.com/clicon/clixon/commit/156660419e8bb1e9d08b645332310e8e4a87b773
