### ISSUE TITLE
Non-obvious behavior of clixon_snmp after snmpset command when transaction validation returns an error

### ISSUE THREAD

**Issue by vvsosed** [clicon/clixon#375]
If we try to change the value using the snmpset command with the value that causes tgcad_clixon_plugin_validate returns an error then the operation is declined. However, after this operation, the clixon backend stores the wrong value in the candidate database. So following well-formed snmpset command after the wrong one fails too. I think it happens because following transaction data is concatenated with the previous bad transaction in the candidate database. As it seems to me now, we cannot reset the candidate database through snmp in any way, so I consider that any other snmpset command will be blocked.
The only way to fix this now is to call discard via the netconf interface. But I don't see any way how to overcome this issue through snmp only.
To solve the problem, I suggest automatically clearing the candidate database in case if the ongoing change was received from snmp and causes tgcad_clixon_plugin_validate returns an error.

**Comment by olofhagsand** [comment]
Fixed by discarding candidate if commit fails

**Comment by vvsosed** [comment]
As a whole, the problem was fixed, but one annoying issue still exists. 
In case when "snmpset" command was declined in clixon by validation procedure I think that an appropriate error message should be printed. But, unfortunately, now it is absent. I think that such behavior will entangle because currently, the error output writes only in the log file, and for someone who used snmpset the result of execution will seem successful for this case.

**Comment by olofhagsand** [comment]
Fixed by validating writes on ACTION instead of COMMIT since libnetsnmp seems not to accept commit errors
