### ISSUE TITLE
must statement check int value failed

### ISSUE THREAD

**Issue by kelin-Monster** [clicon/clixon#386]
Hi:

EX：
container sum {
        leaf add1 {
            type uint32;
        }
        leaf add2 {
            type uint32;
            must "current() > ../add1" {
                error-message "check fail";
            }
        }
    }

if add1=5, add2=10, then the must statement will check failed.

**Comment by olofhagsand** [comment]
This should be fixed by: https://github.com/clicon/clixon/commit/b67ef69b7fffcbe52b8f4da4293d24b1cc80385e
Please verify
