### ISSUE TITLE
Explicit retrieval does not apply xpath filter to non-configuration data nodes

### ISSUE THREAD

**Issue by joc-se** [clicon/clixon#387]
The server returns all non-configuration data nodes when combining explicit retrieval mode with an xpath filter in a get operation.

**Comment by olofhagsand** [comment]
This should be fixed by https://github.com/clicon/clixon/commit/0d41d49fa9a21da8bc14aba77b52ddb9878b57f4

**Comment by joc-se** [comment]
Verified by "test_leafref_state.sh" when default retrieval mode is "explicit" (issue # 384).
