### ISSUE TITLE
RFC6022 (YANG Module for NETCONF Monitoring) 

### ISSUE THREAD

**Issue by SCadilhac** [clicon/clixon#39]
Hello,

I'm just discovering this project, this is great work really!
Just wondering whether implementing [RFC6022](https://tools.ietf.org/html/rfc6022) (streaming of Yang models via Netconf) is somewhat planned?

Thanks,

Sylvain

**Comment by olofhagsand** [comment]
No, I have not received a request on this before. Was it any specific sub-part you were interested in, I am interested in the use-case?
Best
--Olof

**Comment by SCadilhac** [comment]
I'm using a network orchestration tool which (optionally) relies on this RFC to automatically retrieve the supported models from the device, for a smooth integration.

1. The supported Yang models must be advertised as capabilities by the device in the `hello` message.
2. The orchestrator issues a `get > filter > netconf-state > schemas` to check the list of available Yang (or Yin, or XSD...) models directly served by the device.
3. Then the orchestrator can issue a `get-schema` for each schema it needs to download.

**Comment by olofhagsand** [comment]
Ok, I need to look at that a little more closely to understand how much work this would be. Would you be interestwd in contributing?

**Comment by SCadilhac** [comment]
Im looking at the Clixon's code in order to evaluate the needed work too...
By the way, it seems that the announced capabilities follow the older form, e.g. `urn:ietf:params:xml:ns:netconf:capability:candidate:1:0` instead of `urn:ietf:params:netconf:capability:candidate:1.0`. Any reason for that?

**Comment by olofhagsand** [comment]
No reason, apart from following the original RFC.

**Comment by olofhagsand** [comment]
@SCadilhac clixon will be updated with new announced netconf capability: urn:ietf:params:netconf:capability:yang-library:1.0 in 3.8 (October). Following RFC 7895 and RFC 7950.
Aim for RFC 6022 in 3.9.

**Comment by SCadilhac** [comment]
Hi @olofhagsand, great work thank you!
I had started coding a part of it too, but had to temporary switch back to another project, sorry I haven't been of more help so far.

**Comment by SCadilhac** [comment]
Hi @olofhagsand, I had a quick look at the develop branch, and I'm not sure to understand why you removed the basic capabilities, such as `urn:ietf:params:netconf:base:1.0`. My understanding is that `yang-library` should be an additional capability, not the single one.

Example:

```
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.1</capability>
    <!-- Add here other capabilities like validate, candidate, etc. -->
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring?module=ietf-netconf-monitoring&revision=2010-10-04</capability><!-- As per RFC 6022 -->
    <capability>urn:ietf:params:netconf:capability:yang-library:1.0?revision=2016-06-21&amp;module-set-id=[id]</capability><!-- As per RFC 7895 and 7950 -->
  </capabilities>
</hello>
```
Notes:
* It seems that special character escaping is required in Netconf, e.g. `&` becomes `&amp;`.
* The namespace from the Yang module must match the `xmlns` attribute of the root branch modeled by that module in the configuration (RPC response to `get-config`).

**Comment by olofhagsand** [comment]
@SCadilhac  thanks. Added back the netconf announcements of capabilities in hello. When reading RFC7950 Sec 5.6.4 I interpreted it first as yang module library as _replacing_ the capability announcement in Netconf RFC6241 Sec 8. But it doesnt say that- RFC7895 seems to be an additional way to announce capabilities - or actually modules and their features which seem to be similar to the netconf capability announcement, but not the same. It is a little confusing. 
I am glad for your assistance.

**Comment by SCadilhac** [comment]
Hi @olofhagsand,

I've made some testing, and have seen the following issues:
* clixon only understands the legacy `]]>]]>`-based framing mechanism (see RFC6242, section 4), so it should only advertises `urn:ietf:params:netconf:base:1.0` capability (and not 1.1).
* Single quotes should be accepted around XML parameters such as `<blabla xmlns='namespace'>`.
* Character escaping like `&amp;` shouldn't be followed by a space (character escaping but also parsing).
* The revision shouldn't be between quotes in `urn:ietf:params:netconf:capability:yang-library:1.0?revision=%s&module-set-id=%s`.
* The `urn:ietf:params:netconf:capability:writable-running:1.0` capability should be announced.
* The namespace (xmlns) attribute of modules-state is not passed by the Netconf agent.

I've changed the code for a few of these items already, do you want a PR?

**Comment by olofhagsand** [comment]
Yes please!

**Comment by SCadilhac** [comment]
PR submitted. For the last issue (namespace attribute of `modules-state`), I have to dig into the code to understand why `xmlns` is lost on the way...

**Comment by SCadilhac** [comment]
`xml_merge` doesn't seem to preserve `xmlns`.

**Comment by SCadilhac** [comment]
I have patched `xml_merge` as follows: https://github.com/clicon/clixon/commit/d858f4c61412c7061a5bb2357e295db79902ec82
But the other Netconf operations such as `get-config` also need to add the right namespace (`xmlns`) at the roots of the tree. Need a global change here?

Also noticed that `conformance-type`, although mandatory, is not announced by the current code. See https://github.com/clicon/clixon/commit/d858f4c61412c7061a5bb2357e295db79902ec82.

**Comment by olofhagsand** [comment]
@SCadilhac  maybe you can submit individual issues on the remaining errors (not in https://github.com/clicon/clixon/pull/45)? Such as:
- legacy ]]>]]>-based framing
- Single quotes should be accepted around XML parameters
etc, since it is easier to keep track of them that way. I can do it too otherwise.

**Comment by SCadilhac** [comment]
Hi @olofhagsand,
Thanks for the feedback. I've logged new issues so that each error can be followed in a clear way.

**Comment by olofhagsand** [comment]
Closing this since it diverged and split into sub-items, eg https://github.com/clicon/clixon/issues/50
