### ISSUE TITLE
snmpwalk without specific OID doesn't show proprietary OIDs

### ISSUE THREAD

**Issue by doron2020** [clicon/clixon#396]
Hello, it is Siklu team

General snmpwalk is finished without the "No more variables left" line, and  it doesn't show any proprietary OIDs (beginning with iso.3.6.1.4...)
Only a specific OID snmpwalk will show them
If we change the proprietary OIDs to begin with iso.3.6.1.2... then it will show them as well.

doronb@dali:~$ snmpwalk -v2c -c public 10.40.0.156
iso.3.6.1.2.1.1.1 = STRING: "MH-N366"
iso.3.6.1.2.1.1.2 = OID: iso.3.6.1.4.1.31926.35
iso.3.6.1.2.1.1.3 = Timeticks: (586100) 1:37:41.00
iso.3.6.1.2.1.1.4 = ""
iso.3.6.1.2.1.1.5 = STRING: "dorond"
iso.3.6.1.2.1.1.6 = ""
iso.3.6.1.2.1.1.7 = INTEGER: 2
iso.3.6.1.2.1.2.1 = INTEGER: 3
iso.3.6.1.2.1.2.2.1.1.3 = INTEGER: 3
iso.3.6.1.2.1.2.2.1.1.4 = INTEGER: 4
iso.3.6.1.2.1.2.2.1.1.5 = INTEGER: 5
iso.3.6.1.2.1.2.2.1.1.7 = INTEGER: 7
iso.3.6.1.2.1.2.2.1.2.3 = STRING: "eth1 RJ-45 10Gbps"
iso.3.6.1.2.1.2.2.1.2.4 = STRING: "eth2 RJ-45 1Gbps"
iso.3.6.1.2.1.2.2.1.2.5 = STRING: "eth3 SFP+ 10Gbps"
iso.3.6.1.2.1.2.2.1.2.7 = STRING: "Host CPU interface"
iso.3.6.1.2.1.2.2.1.3.3 = INTEGER: 6
iso.3.6.1.2.1.2.2.1.3.4 = INTEGER: 6
iso.3.6.1.2.1.2.2.1.3.5 = INTEGER: 6
iso.3.6.1.2.1.2.2.1.3.7 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.4.3 = INTEGER: 1500
iso.3.6.1.2.1.2.2.1.4.4 = INTEGER: 1500
iso.3.6.1.2.1.2.2.1.4.5 = INTEGER: 1500
iso.3.6.1.2.1.2.2.1.4.7 = INTEGER: 1500
iso.3.6.1.2.1.2.2.1.5.3 = Gauge32: 1000000000
iso.3.6.1.2.1.2.2.1.5.4 = Gauge32: 1000000000
iso.3.6.1.2.1.2.2.1.5.5 = Gauge32: 4294967295
iso.3.6.1.2.1.2.2.1.5.7 = Gauge32: 10000000
iso.3.6.1.2.1.2.2.1.6.3 = Hex-STRING: 00 24 A4 16 4E BA
iso.3.6.1.2.1.2.2.1.6.4 = Hex-STRING: 00 24 A4 16 4E B9
iso.3.6.1.2.1.2.2.1.6.5 = Hex-STRING: 00 24 A4 16 4E BB
iso.3.6.1.2.1.2.2.1.6.7 = Hex-STRING: 00 24 A4 16 4E B9
iso.3.6.1.2.1.2.2.1.8.3 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.8.4 = INTEGER: 2
iso.3.6.1.2.1.2.2.1.8.5 = INTEGER: 2
iso.3.6.1.2.1.2.2.1.8.7 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.10.3 = Counter32: 144840
iso.3.6.1.2.1.2.2.1.10.4 = Counter32: 0
iso.3.6.1.2.1.2.2.1.10.5 = Counter32: 0
iso.3.6.1.2.1.2.2.1.11.3 = Counter32: 642
iso.3.6.1.2.1.2.2.1.11.4 = Counter32: 0
iso.3.6.1.2.1.2.2.1.11.5 = Counter32: 0
iso.3.6.1.2.1.2.2.1.13.3 = Counter32: 642
iso.3.6.1.2.1.2.2.1.13.4 = Counter32: 0
iso.3.6.1.2.1.2.2.1.13.5 = Counter32: 0
iso.3.6.1.2.1.2.2.1.14.3 = Counter32: 0
iso.3.6.1.2.1.2.2.1.14.4 = Counter32: 0
iso.3.6.1.2.1.2.2.1.14.5 = Counter32: 0
iso.3.6.1.2.1.2.2.1.16.3 = Counter32: 0
iso.3.6.1.2.1.2.2.1.16.4 = Counter32: 0
iso.3.6.1.2.1.2.2.1.16.5 = Counter32: 0
iso.3.6.1.2.1.2.2.1.17.3 = Counter32: 0
iso.3.6.1.2.1.2.2.1.17.4 = Counter32: 0
iso.3.6.1.2.1.2.2.1.17.5 = Counter32: 0
iso.3.6.1.2.1.2.2.1.20.3 = Counter32: 0
iso.3.6.1.2.1.2.2.1.20.4 = Counter32: 0
iso.3.6.1.2.1.2.2.1.20.5 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.15.5 = Gauge32: 10000
> (finished but without "No more variables left in this MIB.." line)

Now If I do specific snmpwalk I can see the proprietary OIDs

doronb@dali:~$ snmpwalk -v2c -c public 10.40.0.156 1.3.6.1.4.1.31926.85.3
iso.3.6.1.4.1.31926.85.3.1.1.3.71.112.115 = INTEGER: 3
iso.3.6.1.4.1.31926.85.3.1.1.4.101.116.104.49 = INTEGER: 11
iso.3.6.1.4.1.31926.85.3.1.1.4.101.116.104.50 = INTEGER: 9
iso.3.6.1.4.1.31926.85.3.1.1.4.101.116.104.51 = INTEGER: 10
iso.3.6.1.4.1.31926.85.3.1.1.7.77.72.45.78.51.54.54 = INTEGER: 1
iso.3.6.1.4.1.31926.85.3.1.1.8.66.97.115.101.98.97.110.100 = INTEGER: 2
iso.3.6.1.4.1.31926.85.3.1.1.10.66.111.111.116.108.111.97.100.101.114 = INTEGER: 8
iso.3.6.1.4.1.31926.85.3.1.1.11.82.70.32.115.101.99.116.111.114.32.49 = INTEGER: 4
iso.3.6.1.4.1.31926.85.3.1.1.11.82.70.32.115.101.99.116.111.114.32.50 = INTEGER: 5
iso.3.6.1.4.1.31926.85.3.1.1.11.82.70.32.115.101.99.116.111.114.32.51 = INTEGER: 6
iso.3.6.1.4.1.31926.85.3.1.1.11.82.70.32.115.101.99.116.111.114.32.52 = INTEGER: 7
...
iso.3.6.1.4.1.31926.85.3.1.16.3.71.112.115 = No more variables left in this MIB View (It is past the end of the MIB tree)

Attached the yang file of the proprietary mib

Thanks!

[radio-bridge-tg-inventory.yang.txt](https://github.com/clicon/clixon/files/10353087/radio-bridge-tg-inventory.yang.txt)

**Comment by krihal** [comment]
Hi,

I'll try to reproduce this one and see if we can find the issue. 

Thanks,
/K

**Comment by shmuelhazan** [comment]
@krihal Do you have any update regarding this issue? Do you need anything from us in order to resolve it?

**Comment by krihal** [comment]
If I understand it correctly you have extended the system MIB with proprietary OIDs? Can you explain a bit how that is implemented and also share the MIBs used?

**Comment by doron2020** [comment]
We have understood that it is normal behavior of snmpwalk since its default when no oid argument is subtree .1.3.6.1.2.1
