### ISSUE TITLE
Netconf commit confirm session-id mismatch

### ISSUE THREAD

**Issue by olofhagsand** [clicon/clixon#407]
In some cases in confirm-commit the session-id is wrong, it was taken from a global assigned next-value instead of the session-id of the incoming session.
The cases are when canceling a confirm commit and rollbacks and can be considered as cornercases.
The error is a cornercase but can be triggered by interleaving an extra session between the commit and cancel.

**Comment by dima1308** [comment]
@olofhagsand we verified that the issue is solved.
