### ISSUE TITLE
Request to suppress auto-completion for "deprecated" / "obsolete" status and warn the user.

### ISSUE THREAD

**Issue by navaneethyv** [clicon/clixon#410]
Hello !

From yang spec for keyword status
```
   o  "deprecated" indicates an obsolete definition, but it permits new/
      continued implementation in order to foster interoperability with
      older/existing implementations.

   o  "obsolete" means the definition is obsolete and SHOULD NOT be
      implemented and/or can be removed from implementations.```

[Slack Message](https://clixondev.slack.com/archives/C9NKJEXML/p1674468367732109)

Request to disable auto-completions for "obsolete" and "deprecated" keywords & provide warning if such an input is provided via CLI.

**Comment by navaneethyv** [comment]
Suggestion on the behaviour.
 * "deprecated" and "obsolete" should both prevent the auto completion. 
 *  "deprecated" shall accept the config with a warning [ <node X> is deprecated ]
 *  "obsolete" nodes should not accept the configs at all IMO. [ This is my reading from the spec, happy to be corrected otherwise]

**Comment by olofhagsand** [comment]
My proposal is:
- Do not generate any CLI syntax for obsolete elements (SHOULD NOT be implemented), that is leave it out altogether.
- Accept deprecated syntax and generate completion. Publish a warning at startup.

**Comment by olofhagsand** [comment]
Please verify
