### ISSUE TITLE
Feature Request: validate identities

### ISSUE THREAD

**Issue by dcornejo** [clicon/clixon#42]
An example of this problem exists in the ietf-interfaces YANG.

In clixon it seems I can put anything into /interfaces/interface=<if>/type field and it is happy. clixon should validate those values to those allowed by the YANG model.

For interface types you can look at iana-if-type.yang.

**Comment by olofhagsand** [comment]
Identities were a part of the new features 3.7, including validation and CLI completion support.
Please provide bug reports if the functionality does not work as expected.
