### ISSUE TITLE
if-feature always negative if imported from another module

### ISSUE THREAD

**Issue by shmuelhazan** [clicon/clixon#429]
## Setup
Clixon master (447b8eb1d39af50729dfdeee63859766569c3958)
## Steps to reproduce
1. Apply the following patch: https://github.com/clicon/clixon/commit/0c31647c5e1402dd8a1993a032f3e9bf4aa2a855
2. run unit tests.
## Expected behavior
unit tests should pass, as `ietf-routing:router-id` has been explicitly enabled in the config file. 
## Actual behavior
unit tests fails:
```
Error in Test21 [netconf set extra element under y2 (expect fail)]:
Expected

#410
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="42"><rpc-error><error-type>application</error-type><error-tag>unknown-element</error-tag><error-info><bad-element>kallekaka</bad-element></error-info><error-severity>error</error-severity><error-message>Failed to find YANG spec of XML node: kallekaka with parent: y2 in namespace: urn:example:clixon</error-message></rpc-error></rpc-reply>
##

Received: 
#92
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="42"><ok/></rpc-reply>
##
```

**Comment by olofhagsand** [comment]
Just double-check the patch: https://github.com/shmuelhazan/clixon/commit/9d147491bf543ec3179ca6c948cba883527cf3b2
should it really be "leaf y2 {" on line 22
and "testrun y1 true" on line 212
Should it not be eg y1 in both places?

**Comment by shmuelhazan** [comment]
@olofhagsand You are correct. I updated the patch (and the description); https://github.com/clicon/clixon/commit/0c31647c5e1402dd8a1993a032f3e9bf4aa2a855

**Comment by olofhagsand** [comment]
I guess this is fixed now, @shmuelhazan please close if fixed.
