### ISSUE TITLE
Use Clixon without datastore?

### ISSUE THREAD

**Issue by mico-micic** [clicon/clixon#431]
Hi,
I have a (maybe) special case: We use Clixon for NETCONF / RESTCONF on a device that currently keeps the configuration in its own file. With our Clixon backend plug-in we read and write the device config file. For now, we therefore need Clixon primarily for communication and actually without its own datastore. Is there a way to "disable" the store and handle all read / write operations by the custom backend plug-in? (Actually our solution works but we have two datastores at the end.)

Best regards,
Mico

**Comment by dima1308** [comment]
Hi Mico,
Which operating system your device using? Is it Linux?
If yes, maybe you can create a datastore files in the ramdisk

**Comment by mico-micic** [comment]
I agree with you that this is not a normal case. We also think that it would be best to change the configuration values only through NETCONF/RESTCONF. However, there is still a long way to go before we can change our devices.

Therefore, one more question: How much effort do you think it would take to extend Clixon so that it works without data storage? Just so I can estimate if it is worthwhile to do further research in this direction. Thanks!

**Comment by dima1308** [comment]
If I understand you correctly, you need to add a new CLIXON front-end that will allow you modifying datastore using your proprietary API without using existing CLIXON front-ends Netconf/restconf/SNMP).
Is my understanding correct?

**Comment by mico-micic** [comment]
No, the other way round :) I want to use Clixon for NETCONF/RESTCONF/SNMP communication, but the Clixon server should not write the configuration values to its "own" data store. I want to have the following behaviour:

When a configuration change is requested via NETCONF/RESTCONF/SNMP for my YANG module, the transaction is delegated to my backend plug-in. (This is already the case with the transaction functions). After the transaction commit, the Clixon server should NOT write the changed/new values to the internal data store, as my backend plug-in has already written them to the device master configuration file. 

So I would need an additional configuration e.g. in the clixon_plugin_api to disable the storage of configuration values handled by my backend plug-in.

**Comment by olofhagsand** [comment]
There is an internal clixon_datastore API defined in https://github.com/clicon/clixon/blob/master/lib/clixon/clixon_datastore.h
This used to be a pluggable API, but was replaced some years ago with a hardcoded API only supporting a "text-based" datastore, in contrast with a key-store or other structured databases.
The one thing remaining of configurability is the cache-behavior controlled by the `CLICON_DATASTORE_CACHE` option described here: https://clixon-docs.readthedocs.io/en/latest/datastore.html#datastore-caching
It would be easy to add a "CACHE-ONLY" variant which would mean that the configuration is not flushed to datastore, which would mean that the datastore would be in-memory only.
However, this does not seem to be what you have in mind, as I understand  you would want the clixon backend to work with a "pass-thru"  semantics where no configuration state is stored at all.
It would be possible to add a value to the cache option: `DATASTORE_DONT_SAVE` which could have such a behavior and which you could set for your application.-
However I dont know what other consequence this could have. 
For example, the validate/commit behavior is based on a diff of an existing datastore. I guess it would work with always having an empty datastore, but there could be other foreseen consequences.
