### ISSUE TITLE
Question: Are there already default implementations of ietf-system for linux?

### ISSUE THREAD

**Issue by mico-micic** [clicon/clixon#433]
Hi! 
I would be interested to know if there are already implementations for linux for the ietf-system module? It's not in clixon itself, but does anyone know of another project that has already implemented such default modules?

Thanks! Mico

**Comment by olofhagsand** [comment]
You could also try posting on the clixon matrix channel, see README for links

**Comment by mico-micic** [comment]
Ok, thanks!!
