### ISSUE TITLE
Feature request: node's alias for CLI

### ISSUE THREAD

**Issue by EvgeniiVR** [clicon/clixon#434]
Hello Team,
For our data model we are using a set of private and public yang models.
Due to this sometimes CLI looks no so pretty, semantically tricky and even not human readable.
So our idea is to have a feature extension that can be used in top level private yang with augment statement to define nodes with alias just for CLI representation and leave original public yang models as-is under the hood.

**Comment by EvgeniiVR** [comment]
Hello @olofhagsand, 
As I see in 6.3.0 release notes new "alias" extension has been added. Is it tied w/ this FR?

**Comment by olofhagsand** [comment]
Nor should it have been in the CHANGELOG.
Thanks for pointing this out.

**Comment by EvgeniiVR** [comment]
Got it. Thank you for strong support!

**Comment by olofhagsand** [comment]
@EvgeniiVR one thing I see when looking at the alias function. In the CLI one could alias a keyword to an alias, but it will still show in the original when shown as XML.
For example, assume a leaf "orig" renamed to "alias", then 
```
cli> set alias abc
cli> show config | display cli
set alias abc
cli> show config | display xml
<orig>abc></orig>   # <--- original shown
```
To change the symbol completely one needs to modify the YANG node itself which you probably do not want.

**Comment by olofhagsand** [comment]
I also see "alias" will be difficult for non-leafs. Due to existing code.
I will make a leaf-only variant of "alias" for the time being.
