### ISSUE TITLE
Connect to netconf/rest externally

### ISSUE THREAD

**Issue by makramalla** [clicon/clixon#44]
I am currently using the example docker image and had a question.
Is there w way to communicate with the database externally?

To elaborate further, is there way t expose some ports (such as 830 for netconf, and/or 8080 for rest) that would allow communication using an external netconf or rest client?

**Comment by olofhagsand** [comment]
The clixon docker container is very simple. In another project I have added a restconf and netconf agent in separate containers. These can expose the ports you refer to, while they communicate internally with the backend container. I can make that available if there is interest.

**Comment by makramalla** [comment]
I think that would be really effective. That was the docker container will have a full solution an can be used in a more flexible way.

If not you can point me in the right direction and I can try to add it on my end.

**Comment by olofhagsand** [comment]
@makramalla The clixon docker containers have been updated according to: https://github.com/clicon/clixon/blob/master/docker/README.md. The clixon-system container exposes a port (80 by default) for restconf for example. CLixon-system runs the whole system in one container. It is possible to run backend, restconf, nginx, etc in different containers, but then the containers need to communitae by IP internally and is more complex - like a cluster.
