### ISSUE TITLE
test_client.sh needs to be expanded to cover CLIXON_CLIENT_SSH case

### ISSUE THREAD

**Issue by pprindeville** [clicon/clixon#446]
We should probably test IPC and Ssh as the comments state.

**Comment by olofhagsand** [comment]
Actually, the client API is currently somewhat outdated as stated in https://clixon-docs.readthedocs.io/en/latest/client.html. An effort is being made to replace it with https://github.com/clicon/clixon-pyapi currently being worked on.
The test_client.sh should maybe even be obsoleted.
