### ISSUE TITLE
Choice and Leafref

### ISSUE THREAD

**Issue by temabeloglinski** [clicon/clixon#469]
Hi Olof
I have a question about choice function and leafref.
For example I have this yang structure:

            choice myChoice {
                description "Fruit or Flowers";
                case fruit {
                   leaf fruit-name {
                     description "Fruit name";
                     type leafref {
                      path "../../fruits/name";
                     }
                  }
                }
                case flower {
                   leaf flower-name {
                     description "Flower name";
                     type leafref {
                      path "../../flowers/name";
                     }
                  }
              }
            }
But if I call commit, clixon returns an error - Nov 30 22:01:44: Commit failed. Edit and try again or discard changes: application operation-failed No referred YANG node found for leafref path ../../flowers/name.
In this case, the names of objects are called up when I click on the question mark, i.e. the paths are correct.
What could be the problem?

**Comment by temabeloglinski** [comment]
Yes of course.
I simplified the configuration:

list fruits {
key "name";
leaf name {
type string;
}
}

list flowers {
key "name";
leaf name {
type string;
}
}

            choice myChoice {
                description "Fruit or Flowers";
                case fruit {
                   leaf fruit-name {
                     description "Fruit name";
                     type leafref {
                      path "../fruits/name";
                     }
                  }
                }
                case flower {
                   leaf flower-name {
                     description "Flower name";
                     type leafref {
                      path "../flowers/name";
                     }
                  }
              }
            }

root@cli/> show configuration cli
set flowers 123
set flowers 2345

root@cli/> set flower-name ?
  123                   Flower name
  2345                  Flower name
  <flower-name>         Flower name

root@cli/> set flower-name 123 <Enter>

root@cli/> show configuration cli
set flowers 123
set flowers 2345
set flower-name 123

root@cli/> commit
Nov 30 23:16:42: Commit failed. Edit and try again or discard changes: application operation-failed No referred YANG node found for leafref path ../flowers/name
root@cli/>

**Comment by olofhagsand** [comment]
Thanks, will have a look

**Comment by temabeloglinski** [comment]
Hi Olof!
Did you manage to reproduce the error?

**Comment by khromenokroman** [comment]
Hi, I have such a problem, is there a solution to it?

**Comment by olofhagsand** [comment]
Sorry, been busy, will try to look at it tomorrow

**Comment by olofhagsand** [comment]
Confirmed this issue

**Comment by olofhagsand** [comment]
Should be fixed now. I dont think the combination of choice and leafref has ever worked.
Added regression test.
@temabeloglinski @khromenokroman please verify and if it works, close the issue

**Comment by temabeloglinski** [comment]
Hi Olof!
Thank's a lot!
Everything is working.
