### ISSUE TITLE
Add support for -V option to give version

### ISSUE THREAD

**Issue by pprindeville** [clicon/clixon#472]
Rather than doing `echo -e "show version\nexit\n" | clixon_cli` it would be nicer to just have `clixon_cli -V` give an answer.

That said, the version string should be one provided by the developer, not simply `CLIXON_VERSION_STRING`, etc.

**Comment by olofhagsand** [comment]
One complexity is plugins must be loaded before a callbacks are called.
This means that you need to have a proper install, configuration-file etc.
You cant just type `clixon_cli -V` on a bare binary.
One could consider a simpler variant just returning CLIXON_VERSION_STRING and exit.

**Comment by olofhagsand** [comment]
Also, should version string be printed on stderr ot stdout?

**Comment by pprindeville** [comment]
Working backwards, I'd print to `stdout` because it's not a error, and I might want capture it in `$(...)` anyway.

What about an external static pointer to a string constant that the user is required to set?

**Comment by olofhagsand** [comment]
stdout: OK
static ptr: No, same problem, still need to load plugin code (where the static pointer points to), and in order to find the plugin code you need the config file.

**Comment by olofhagsand** [comment]
Committed -V with first a mandatory CLIXON_VERSION followed by customized plugin callbacks.
