### ISSUE TITLE
Enum from YANG-Model

### ISSUE THREAD

**Issue by temabeloglinski** [clicon/clixon#478]
Hi Olof!
I have a question about enumeration from yang-model.
Is it possible by any method using Clixon to select data not only about the configured values, but also about all possible values?
For example, via restconf.

**Comment by olofhagsand** [comment]
You can get the YANG schema itself via netconf or restconf.

**Comment by olofhagsand** [comment]
Yes,in RFC 6022, for example,ietf-netconf-monitoring.yang  defines container schemas state and get-schema RPC, to retrieve the YANG definitions. Clixon sypports this by default. See option `CLICON_NETCONF_MONITORING`.
There is also the module-set including a module list in RFC8525 ietf-yang-library.yang that lists the modules.
That is about getting the schema.

Regarding enum values, a recent commit improved the enum/value API by two new functions: `yang_enum2int() `and `yang_enum_int_value().` 

Maybe this is more what you are looking for?
