### ISSUE TITLE
Question about clixon notification

### ISSUE THREAD

**Issue by temabeloglinski** [clicon/clixon#489]
Hi Olof!
I have a question abot clixon notification.
When I print error messages, I would like to hide the standard clixon messages.
How can I do that?
Is there a configuration setting that does this?

For example

```
root@cli/> commit
Feb  2 21:30:41: clicon_rpc_commit: 1552: Netconf error: Commit failed. Edit and try again or discard changes: application operation-failed destination-address are not configured
CLI command error
root@cli/>
```

**Comment by khromenokroman** [comment]
I am also interested in this, I would like to remove unnecessary messages

**Comment by olofhagsand** [comment]
We just modified the error/log API but which includes a customizable error:
https://clixon-docs.readthedocs.io/en/latest/errors.html#customization
There is also the ability to redirect the error via the `-l <option>` command-line option, see  https://clixon-docs.readthedocs.io/en/latest/errors.html#debugging
But I see here that even if you direct `-l none`  you will still get some error on stderr:  https://github.com/clicon/clixon/blob/4e3bd6fbdd94fcbfdcb856e94dc8d7d3f2230417/apps/cli/cli_plugin.c#L490
How do you want the behavior: do you not want any message on stderr?

**Comment by temabeloglinski** [comment]
Thanks Olof.
-l syslog - that's what I need.
