### ISSUE TITLE
Improve namespace handling

### ISSUE THREAD

**Issue by SCadilhac** [clicon/clixon#49]
As discussed in #39, the namespaces should be properly tagged using the `xmlns` attributes in the various XML representations, based on the corresponding Yang models.

**Comment by olofhagsand** [comment]
There are more examples of not correct namespace handling. 
In the following restconf example "example-jukebox:" is ignored:
     GET /restconf/data/example-jukebox:jukebox/
It still (usually) works since the topnodes are scanned, but is not correct.
Same for netconf cases, such as:
 <rpc message-id="101"
          xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"
          xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
and others.

**Comment by olofhagsand** [comment]
Namespaces should now be properly tagged with xmlns attribute for both netfonf and restconf. JSON uses module names for indicating namespaces. There is still a default namespace, so it is possible to call <rpc> which means <rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">.
This is valid for the develop branch which will be merged into master and 3.9 during January.
