### ISSUE TITLE
Netconf delete/remove operation doesn‘t work？

### ISSUE THREAD

**Issue by magicalfox007** [clicon/clixon#531]
I use clixon-4.2.0
It seems that netconf delete/remove operation doesn't work.

rpc example:
`<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><edit-config><target><candidate/></target><default-operation>none</default-operation><config><interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces"><interface operation="delete"><name>agg1</name></interface></interfaces></config></edit-config></rpc>]]>]]>`

reply is ok:
`<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><ok/></rpc-reply>]]>]]>`

but content in database <candidate> didn't change: (the target interface still exist)
`<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
      <interface>
         <name>agg1</name>
         <description>agg1</description>
         <enabled>false</enabled>
      </interface>......`

**Comment by olofhagsand** [comment]
Possibly one should return a proper error message, but it is problematic with unknown attributes (`operation` in namespace `urn:ietf:params:xml:ns:yang:ietf-interfaces` . Clixon currently just ignores them.

**Comment by magicalfox007** [comment]
Thx for reply, <operation> tag seems to be ignored if nc is not specifified，the request will be treated as a merge operation.
