### ISSUE TITLE
Protocol error: clicon_rpc: Socket unexpected close

### ISSUE THREAD

**Issue by mihmax189** [clicon/clixon#537]
Hi! 

I built and installed the clicon. I built and installed example/ntp. Started clicon_backend and clicon_cli. When I change a certain parameter of ntp described in its yang model, I get an error. 

After that I can't change the parameters. 

![Снимок экрана 2024-07-29 142755](https://github.com/user-attachments/assets/2bd4894d-bf8a-4093-8603-b087422d5725)

**Comment by olofhagsand** [comment]
It seems you built and tried to run "clicon/clicon", since you refer to the NTP example.
If so, you should instead try "clicon/clixon", which is the active repo, the other is historical.

**Comment by mihmax189** [comment]
Yes, I was referring to the clicon project. I apologize for opening an issue in the clixon project. I was inattentive. 

Thanks for the reply.
