### ISSUE TITLE
How to set data restconf

### ISSUE THREAD

**Issue by mihmax189** [clicon/clixon#538]
Hi!

You have a good example in your project how to set values in yang model using netconf. 

https://github.com/clicon/clixon/blob/master/example/main/README.md

Item Using Netconf
The following example shows how to set data using netconf...

```
sh> clixon_netconf -qf /usr/local/etc/clixon/example.xml
<?xml version=“1.0” encoding=“UTF-8”?
<hello xmlns=“urn:ietf:params:xml:ns:netconf:base:1.0”><capabilities><capability>urn:ietf:params:netconf:base:1.0</capability></capabilities></hello>]]>]]>
<rpc xmlns=“urn:ietf:params:xml:ns:netconf:base:1.0” message-id=“0”>
   <edit-config>.
      <target><candidate/></target>
      <config>
         <table xmlns=“urn:example:clixon”>
            <parameter>
               <name>a</name>
               <value>42</value>
            </parameter>
         </table>
      </config>
   </edit-config>
</rpc>]]>]]>
# Reply: <rpc-reply xmlns=“urn:ietf:params:xml:ns:netconf:base:1.0” message-id=“0”><ok/></rpc-reply>]]>]]>]]>
<rpc xmlns=“urn:ietf:params:xml:ns:netconf:base:1.0” message-id=“1”>
   <commit/>
</rpc>]]>]]>]]>
```

Can I use restconf to set values in the same way? If yes, please provide an example curl query.

For example:

curl -X GET http://127.0.0.1/restconf/data/clixon-example:table/parameter=a/value - get the value of a parameter named a.

Is there a POST request to set a new value of parameter a. And a request to create a new parameter with a new name and value?

**Comment by olofhagsand** [comment]
You can look i RFC 8040 or for example, examples im the test dir, eg here: https://github.com/clicon/clixon/blob/master/test/test_restconf.sh

In short, POST adds an object "below" the addressed, whereas PUT "replaces" it.
Something like:
```
curl -X PUT -H "Content-Type: application/yang-data+json" http://127.0.0.1/restconf/data/clixon-example:table/parameter=a/value -d '{"clixon-example:value": "foo"}' 
curl -X POST -H "Content-Type: application/yang-data+json" http://127.0.0.1/restconf/data/clixon-example:table/parameter=a -d '{"clixon-example:value": "foo"}' 
```
