### ISSUE TITLE
When are the restconf_client_rpc and netconf_client_rpc functions called?

### ISSUE THREAD

**Issue by mihmax189** [clicon/clixon#539]
Hi!

I apologize for the large number of questions. Could you please explain when the restconf_client_rpc function defined in example_restconf.c and the netconf_client_rpc function defined in example_netconf.c, example_rpc in example_backend.c are called?

Can they be called via restconf and netconf queries? 

Can you explain what the backend, netconf, restconf plugins are for? It's not very clear from the project documentation.

I have no way of understanding this. Thanks.

**Comment by olofhagsand** [comment]
Plugins are described here: https://clixon-docs.readthedocs.io/en/latest/plugins.html
Plugins add application semantics. Backend plugins are the main routines, primarily handling the datastore transactions.
cli/netconf are clients (not end-user clients though) and the restconf process to the backend for cases where a direct client application semantics needs to be defined.
This is most clear for CLI callbacks, which are called directly when a CLI command is executed locally in the cli client process. Typically, a cli callback initiates an internal NETCONF RPC with the backend, ie translating the CLI command to NETCONF commands that the backend understands.
In the same way, the netconf and restconf clients can be used to add semantics directly by the netconf client or restconf process, but is less common. One typical restconf plugin is the auth plugin for example which is best done by the restconf process before it communicates with the backend.
Note there is also a chat forum for questions.

**Comment by mihmax189** [comment]
Thanks for the detailed response.
