### ISSUE TITLE
Issue with bare axis names (XPath 1.0)

### ISSUE THREAD

**Issue by achernavin22** [clicon/clixon#54]
If you have a node in your scheme that has a name of one of
the axes, it leads to an invalid path. For instance, for the `child` axis:
```
/ipsec-config/tunnel[instance='1']/crypto/ike/child/name
```
Sorry, I don't have the exact error now but it was something like this:
```
... clixon_xpath_parseerror ... line 1 ... after or before "/"
```
At the same time, this path is considered as valid:
```
/ipsec-config/tunnel[instance='1']/crypto/ike/proposals/name
```
Both "child" and "proposals" are lists.

**Comment by olofhagsand** [comment]
@achernavin22 please supply yang spec (or part of it - is that ietf-ipsec@2016-03-09.yang?) and preferably action leading to the error? (eg a configuration or cli commands).

**Comment by achernavin22** [comment]
YANG spec:
```
container ipsec-config {
    list tunnel {
        key "instance";
        leaf instance {
            type uint32;
        }
        ...
        container crypto {
            ...
            container ike {
                ...
                list proposals {
                    key "name";
                    leaf "name" {
                        type string;
                    }
                    ...
                }
                ...
                list child {
                    key "name";
                    leaf name {
                        type string;
                    }
                    ...
                }
            }
        }
    }
}
```

Can be reproduced having this in your clispec file (try to TAB or execute the command):
```
<name:string expand_dbvar("candidate","/ipsec-config/tunnel=%s/crypto/ike/child-sa=%s/name")>
```

**Comment by olofhagsand** [comment]
Confirmed: "If you have a node in your scheme that has a name of one of the axes, it leads to an invalid path."
Need some more time to fix this.

**Comment by olofhagsand** [comment]
This is fixed for axis-names. However, I think there may be other corner-cases since https://www.w3.org/TR/xpath-10 is somewhat tricky in this respect.
