### ISSUE TITLE
CLI help text for YANG data model with multi-line description field is misformatted 

### ISSUE THREAD

**Issue by brunorijsman** [clicon/clixon#543]
I used the YANG data model from standard "ETSI GS QKD 015 V2.1.1 (2022-04)"

https://www.etsi.org/deliver/etsi_gs/QKD/001_099/015/02.01.01_60/gs_QKD015v020101p.pdf

The actual YANG data models are provided in the standard PDF itself but also available as separate .yang files in this repo:

https://forge.etsi.org/rep/qkd/gs015-ctrl-int-sdn/tree/v2.1.1

These YANG data models have single-line "description" fields, similar to this:

```
  grouping qkdn_version {
    description "Grouping of qkdn_version leaf.";
    
    leaf qkdn_version {
      type string;
      description "Hardware or software version of the SD-QKD node.";
    }
  }
```

But these YANG data models often have multi-line "description" fields, similar to this:

```
  grouping qkdn_location_id {
    description "Grouping of qkdn_location_id leaf.";
    
    leaf qkdn_location_id {
      type string;
      default "";
      description
        "This value enables the location of the secure
        area that contains the SD-QKD node to be specified.";
    }
  }
```

Note that (a) the actual description line starts on the next line after the description statement and (b) the description spands multiple lines with the opening quote at the beginning at the first line and the closing quote at the ending of the last line.

The corresponding Clixon CLI looks very strange (type question mark after the set command to display help text):

```
/> edit qkd_node
qkd_node> set

                                                                                     ther
                        for internal or external purposes) is considered an application.

                        abstracted as interfaces of the SD-QKD node.
                                                                                  he network.
                                                                               irtual multi-hop
                        connection doing key-relay through several nodes.
  qkdn_capabilities     Capabilities of the SD-QKD node.
  qkdn_id               This value reflects the unique ID of the SD-QKD node.

                        area that contains the SD-QKD node to be specified.
  qkdn_version          Hardware or software version of the SD-QKD node.
qkd_node>
```

There are two problems:

(a) The help text formatting is screwed up.

(b) Attributes are missing from the help text. The above example shows three attributes (qkdn_capabilities, qkdn_id, and qkdn_version) but there are many more attributes in the YANG data model (e.g. qkdn_id, qkdn_status, qkdn_location_id, etc.)

Note: manually editing the .yang data model to get rid of these multi-line descriptions is not an option; this is a standard defined by a third party (namely ETSI).

Version information:

```
clixon_backend -f etsi_015.xml -V
Clixon version: 7.1.0-35-gd6622772 2024-08-18 14:16:38 +0200
Aug 19 13:13:48.237774: clixon_backend: 296 Terminated retval:0

/clixon# git reflog
d6622772 (HEAD -> master, origin/master, origin/HEAD) HEAD@{0}: clone: from https://github.com/clicon/clixon.git

/cligen# git reflog
f5a60ce (HEAD -> master, origin/master, origin/HEAD) HEAD@{0}: clone: from https://github.com/clicon/cligen.git
```

**Comment by olofhagsand** [comment]
Identified as problem with DOS newline mode in the etsi yang file
Workaround: transform to UNIX format

**Comment by olofhagsand** [comment]
Fixed by ignoring \r in cligen parse rules for helptexts. Plz verify.
