### ISSUE TITLE
clixon_backend not running.

### ISSUE THREAD

**Issue by shubhtrix** [clicon/clixon#58]
Hi @olofhagsand

I have been using restconf for past some time and everything working fine. I compile the package with all other dependencies on openwrt platform for ARM. And I'm able to compile it, then problem is when I'm trying to run the clixon_backend on the target it hangs unexpectedly even when I'm trying the same with -F (foreground) options.

You can have a look. 

'
root@OpenWrt:/www-data# clixon_backend -F -s init -D 4 -lf/www-data/.backend.log -f /www-data/configure_restconf/conf.xml -y /www-data/configure_restconf/example.yang

'
Not able to see anything on stdout or on log file.

 Any kind of help would be appreciable. 

Regards,
Shubh

**Comment by olofhagsand** [comment]
I havent tested on ARM. 
- Try clixon_cli or clixon_restconf (same result?)
- Run in gdb with -F. 
- Valgrind?

**Comment by shubhtrix** [comment]
Ya found the problem!!!

See on ARM "char" behaves as a "unsigned char" so under "/apps/backend/backend_main.c" we have a while loop under main inside that you defined **char c**; for **getopt** . So on ARM machine this char c gets a value after all the short-options **c** updates with a value of 255 oxff which never terminates the while loop with **-1** .

**Comment by olofhagsand** [comment]
@shubhtrix what is the fix? Change char to signed char/int8_t? I would like to patch the src to cover this case.

**Comment by shubhtrix** [comment]
@olofhagsand ya sorry for a quick fix on that I applied a simple **int**  not tried with int8_t or signed char. As per the problem is concerned, hopefully both should work (**signed char** and **int8_t**). I'll let you know if the time permits after testing with signed char and int8_t. Untill then be with the same **char** or maybe an **int** because on any x86 arch. it works fine just the ARM which is causing the problem.

**Comment by shubhtrix** [comment]
@olofhagsand Sorry to disturb you again, but ya I've realized that the same thing exists in clixon_restconf, clixon_netconf, example_backend, example_restconf etc. I mean wherever you used **getopt**

**Comment by olofhagsand** [comment]
I understand. I will change so that the char for getopt is signed. NP. Are there other problems on ARM?

**Comment by shubhtrix** [comment]
@olofhagsand sorry for late reply, I don't have any other problem yet. 

But I have a query... "Is it necessary to run the restconf daemon with user : www-data? I mean what if I run the daemon with root user, any problem in that? And if you think any consequences regarding the functionally of the same."

**Comment by olofhagsand** [comment]
There is some related discussion here:
https://github.com/clicon/clixon/issues/37
Also in the slack:
https://clixondev.slack.com/messages/C9M4TC9MW/

**Comment by olofhagsand** [comment]
Outdated question
