### ISSUE TITLE
RPC Callbacks for autocli

### ISSUE THREAD

**Issue by Darry-Zhang** [clicon/clixon#582]
Hello Team,

Assuming I have added two containers, container A and container B, 

and registered two callback functions callback A and callback B in plugin A and plugin B respectively.

I hope that when I input set A "xx" and set B "xx", callback A and callback B will be triggered correspondingly.

May I ask if it can be supported?

I learned about custom commands such as RPC example and example<var: int32>in the example project, 

which can achieve the functions I mentioned above, but I have to do more work in CLI.

**Comment by Darry-Zhang** [comment]
What I mean is that I executed the CLI command (eg: set policy condition c1) on the frontend, and clixon_cli will send an RPC message to the backend, right?

> <rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" cl:username="rain" xmlns:cl="http://clicon.org/lib" message-id="42"><edit-config><target><candidate/></target><default-operation>none</default-operation><config><policy xmlns="urn:example:clixon"><condition nc:operation="replace"><name>c1</name></condition></policy></config></edit-config></rpc>

My initial idea was to register a new RPC callback in the plugin and use the key to listen for commands.
But I don't know how to distinguish between different commands, because whether I execute set A or set B, the backend receives an edit config message.
I want to also listen for this command in the backend plugin and send the command message to other system applications.
How can I complete the listening for this command? Maybe my initial idea was wrong. I should handle these commands during commit.

**Comment by Darry-Zhang** [comment]
What I mean is that I executed the CLI command (eg: set policy condition c1) on the frontend, and clixon_cli will send an RPC message to the backend, right?

`<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" cl:username="rain" xmlns:cl="http://clicon.org/lib" message-id="42"><edit-config><target><candidate/></target><default-operation>none</default-operation><config><policy xmlns="urn:example:clixon"><condition nc:operation="replace"><name>c1</name></condition></policy></config></edit-config></rpc>`

My initial idea was to register a new RPC callback in the plugin and use the key to listen for commands.
But I don't know how to distinguish between different commands, because whether I execute set A or set B, the backend receives an edit config message.
I want to also listen for this command in the backend plugin and send the command message to other system applications.
How can I complete the listening for this command? Maybe my initial idea was wrong. I should handle these commands during commit.

**Comment by olofhagsand** [comment]
You can add a new callback listening to edit-config:
```
   rpc_callback_register(h, your-function,  your-arg, NETCONF_BASE_NAMESPACE, "edit-config")
```
Then your-function will be called before the standard one.
