### ISSUE TITLE
clixon autocli view

### ISSUE THREAD

**Issue by Darry-Zhang** [clicon/clixon#585]
Hello Team,

After using autocli in Clixon, the keywords in all views are "set", "edit", "show", etc,
Can Clixon implement view mode? 
eg: 
"edit interface" is entered, the keywords for the current view become "ipv4", "IPv6", "route", and 
"edit l2" is entered, the keywords for the current view become "vlan", "port", etc.

**Comment by Darry-Zhang** [comment]
@olofhagsand  could you look at my request if possible?

**Comment by olofhagsand** [comment]
See https://clixon-docs.readthedocs.io/en/latest/cli.html#cli-show-auto-mode
Is "view" mode different from "show" in edit mode, if so, in what way, please clarify?
@Darry-Zhang

**Comment by Darry-Zhang** [comment]
edit mode:
rain@rain-server /> edit table
rain@rain-server table> set parameter xx

view mode:
I hope to use other keywords to configure commands instead of always using 'set',ignore 'set'.
eg:
rain@rain-server table> parameter xx
rain@rain-server table> keyword xxx

**Comment by olofhagsand** [comment]
In my example above, the verb "show"  is implicit. How would you do it for "set" or "delete"? How do you specify the implicit verb "set" instead of implicit verb "set"? 
Is this view-mode present in other products BTW?

**Comment by Darry-Zhang** [comment]
@olofhagsand Is there a way to achieve it?
