### ISSUE TITLE
unexpected behaviour of trees in cli file.

### ISSUE THREAD

**Issue by makwen** [clicon/clixon#61]
Hi All, 

I've faced with a strange behaviour, I've changed example_cli.cli: 
```
CLICON_MODE="example:main";
CLICON_PROMPT="%U@%H> ";
CLICON_PLUGIN="example_cli";

treename="main";
example("This is a comment") <var:int32>("Just a random number"), mycallback("myarg");

treename="example";
# Translate variable "value" by incrementing its characters
translate value (<value:string translate:incstr()>),cli_set("/translate/value");
```
and also changed line   <CLICON_CLI_MODE>main</CLICON_CLI_MODE> in example.xml

after standart running #clixon_cli -f example.xml 
I see "example" function in menu as expected, but when I execute it, callback function "mycallback" is NOT invocked. 

Does somebody know why it's happened? 

Thank you,
Maksym

**Comment by olofhagsand** [comment]
Yes, Somewhat obscure - I did not even knew it (half) worked.
There is some interference between cligen creating cli trees without callbacks and clixon code with callbacks.
I extended your example, it is only the "last" tree that works with clixon callbacks,
eg, this works:
  clixon_cli -f /usr/local/etc/example.xml -m foo 
but neither of these work:
  clixon_cli -f /usr/local/etc/example.xml -m main
  clixon_cli -f /usr/local/etc/example.xml -m example

 # 
CLICON_MODE="example:main:foo";
CLICON_PROMPT="%U@%H> ";
CLICON_PLUGIN="example_cli";

treename="example";
example("This is a comment"), mycallback("myarg");

treename="main";
main("This is a comment"), mycallback("myarg");

treename="foo";
foo("This is a comment"), mycallback("myarg");

**Comment by olofhagsand** [comment]
Discrepancies between the CLI in Clixon and CLIgen are described here: https://clixon-docs.readthedocs.io/en/latest/advanced.html#differences-to-cligen
