### ISSUE TITLE
feature request: store modules state in database and respect the stored yang modules

### ISSUE THREAD

**Issue by dcornejo** [clicon/clixon#70]
to properly interpret the database (${CLIXON_XMLDBDIR}/running_db) you need to know what version of the YANG files it was validated with. you could do this by saving information similar to ietf-yang-library:modules-state into the saved database.

additionally, clixon should require the module/revision of the YANG file that is specified in the database and should load only what is specified. if the required version is not available, then this is an error.

this impacts the process of upgrading the YANG files. I'd suggest that this be a manual process so that the user is aware of the impacts of the upgrade and can respond to errors and warnings when the YANG is updated. When the CLI is started, you could detect that a newer version of a YANG module is available and notify the operator.

**Comment by olofhagsand** [comment]
Thanks, 
Relates to the "Handle revisions to data model" roadmap item in [https://github.com/clicon/clixon/blob/develop/ROADMAP.md]

**Comment by olofhagsand** [comment]
A new backend startup and upgrade support feature has been added, see [doc/startup.md] for details. This includes detection of module-state differences, detection of validation failures at startup, a failsafe mode, and provides for a manual upgrade.
