### ISSUE TITLE
Range parsing is not RFC 7950 compliant

### ISSUE THREAD

**Issue by loeliger** [clicon/clixon#71]
A leaf node with a range like this:

<pre>
leaf thing {
    type uint8 {
	range "7 .. 17";
    }
}
</pre>

fails to parse properly even though it is RFC-7950 compliant.
The RFC says:

<pre>
;; Ranges

   range-arg-str       = < a string that matches the rule >
                         < range-arg >

   range-arg           = range-part *(optsep "|" optsep range-part)

   range-part          = range-boundary
                         [optsep ".." optsep range-boundary]

   range-boundary      = min-keyword / max-keyword /
                         integer-value / decimal-value

    optsep              = *(WSP / line-break)

   WSP                 = SP / HTAB
                         ; whitespace
</pre>

I think clixon needs to relax its parsing an allow white spaces
around the three range tokens.

**Comment by olofhagsand** [comment]
This should work

**Comment by olofhagsand** [comment]
Reopening. still broken.

**Comment by olofhagsand** [comment]
Fixed (again)
