### ISSUE TITLE
Implementation in arm64

### ISSUE THREAD

**Issue by danieluribe** [clicon/clixon#72]
Hello,

I'm considering Clixon for a Netconf/Restconf implementation for an embedded device. We have arm64 and arm32 architectures.
As it is said "Clixon runs on Linux, FreeBSD port and Mac/Apple. CPU architecures include x86_64, i686, ARM32.".
Has anyone tested Clixon in an arm64 architecture?

Thank you,
Daniel Uribe

**Comment by olofhagsand** [comment]
There is some ARM discussion here https://github.com/clicon/clixon/issues/58

**Comment by danieluribe** [comment]
I've been using Clixon in arm64 and it works.
