### ISSUE TITLE
Nodes from more than one of the choice's branches exist at the same time

### ISSUE THREAD

**Issue by achernavin22** [clicon/clixon#81]
Given a choice:
```
choice test-choice {
	case first {
		leaf first-node {
			type uint32;
		}
	}

	case second {
		leaf second-node {
			type uint32;
		}
	}
}
```

Via CLI clixon_backend enforces the existence of at most one of the choice's branches but allows more than one via RESTCONF or if the configuration is loaded from a file (startup or just manually saved).

PUT
```
{
	"first-node": 1,
	"second-node": 2
}
```

startup
```
	<first-node>1</first-node>
	<second-node>2</second-node>
```

These examples will successfully pass validation and will be committed.

**Comment by olofhagsand** [comment]
Fixed. 
Note it may still be possible to load a file with multiple choice elements via netconf, but it will not pass validate.
Thanks for reporting.
