### ISSUE TITLE
Cannot write to config using restconf example

### ISSUE THREAD

**Issue by preetjuniper** [clicon/clixon#91]
Hi,

I'm trying to follow the restconf docs to write config to the store: https://github.com/clicon/clixon/blob/master/apps/restconf/README.md#installation. When I issue the sample to write an interface to ietf-interfaces, I get the following error:
```
bash-5.0# curl -sX PUT http://localhost/restconf/data -H 'Content-Type: application/yang-data+json' -d '{"ietf-interfaces:interfaces":{"interface":{"name":"eth1","type":"ex:eth","enabled":false}}}'
{
  "ietf-restconf:errors" : {
  "error": {
    "error-type": "application",
    "error-tag": "unknown-namespace",
    "error-info": {
      "bad-namespace": "ex"
    },
    "error-severity": "error",
    "error-message": "No module corresponding to prefix"
  }
}
```
(I added the Content-Type param otherwise I get `<h1>Unsupported Media Type</h1>` back)

This is on the 'main' docker image with the 'example' configuration and files. nginx, clixon_resconf and clixon_backend are running. I get a list of yang modules when I issue a GET to `http://localhost/restconf/data`, and if I use the CLI to create an interface, I can then query that with restconf

```
nobody@cfcd061ad87c> set interfaces interface eth9 type ex:eth
nobody@cfcd061ad87c> validate
nobody@cfcd061ad87c> commit
...
bash-5.0# curl -G http://127.0.0.1/restconf/data/ietf-interfaces:interfaces
{
    "ietf-interfaces:interfaces": {
      "interface": [
        {
          "name": "eth9",
          "type": "clixon-example:eth",
          "enabled": true
        }
      ]
    }
  }
```
What am I doing wrong?

**Comment by olofhagsand** [comment]
The example is wrong. In Clixon 4.1 I made a major upgrade to the RESTCONF functionality correcting some errors in the RESTCONF handling. But I see now that the apps/restconf/README.md is not updated, sorry about that.
The correct restconf PUT statement should be:
```
curl -sX PUT http://localhost/restconf/data/ietf-interfaces:interfaces -H 'Content-Type: application/yang-data+json' -d '{"ietf-interfaces:interfaces":{"interface":{"name":"eth1","type":"clixon-example:eth","enabled":true}}}'
```
There were three errors:
1) -H Content-Type missing (you fixed that)
2) The URI should be http://localhost/restconf/data/ietf-interfaces:interfaces to match the top-level data object. (This could only have worked if it was a POST)
3) The interface type identity should be the module name, thus: "type":"clixon-example:eth" as shown in the GET statement above.

I will fix the example.
Thanks for detecting this.

**Comment by olofhagsand** [comment]
Fixed above by updating documentation
