### ISSUE TITLE
clixon-lib yang revision file name update

### ISSUE THREAD

**Issue by preetjuniper** [clicon/clixon#92]
I saw the following when trying to start the clixon_backend in the main docker container:
```
Aug 21 20:08:43: yang_parse_filename /usr/local/share/clixon/clixon-lib@2019-06-05.yang
Aug 21 20:08:43: yang_spec_load_dir: 3081: Yang error: Yang module file revision and in yang does not match: /usr/local/share/clixon/clixon-lib@2019-06-05.yang vs 20190813: Invalid argument
```

Does the file need to be renamed? My temp workaround was
```
diff --git a/yang/clixon/Makefile.in b/yang/clixon/Makefile.in
index c982ddc..87d5e65 100644
--- a/yang/clixon/Makefile.in
+++ b/yang/clixon/Makefile.in
@@ -42,7 +42,7 @@ datarootdir     = @datarootdir@
 YANG_INSTALLDIR   = @YANG_INSTALLDIR@
 
 YANGSPECS       = clixon-config@2019-06-05.yang
-YANGSPECS      += clixon-lib@2019-06-05.yang
+YANGSPECS      += clixon-lib@2019-08-13.yang
 YANGSPECS      += clixon-rfc5277@2008-07-01.yang
 YANGSPECS      += clixon-xml-changelog@2019-03-21.yang
 
diff --git a/yang/clixon/clixon-lib@2019-06-05.yang b/yang/clixon/clixon-lib@2019-08-13.yang
similarity index 100%
rename from yang/clixon/clixon-lib@2019-06-05.yang
rename to yang/clixon/clixon-lib@2019-08-13.yang
```

**Comment by olofhagsand** [comment]
I see there is a failure on the revert of a new revision (the intended upgrade of clixon-lib was reverted), but the new revision date is kept.
That is an error, but strangely I do not see it in the CI logs at https://travis-ci.org/clicon/clixon (which run as containers)
I need to dig deeper.
(The fix will most probably be as you made, to include a new revision although with null changes from the old)

**Comment by olofhagsand** [comment]
Fixed above 
 * Clixon-lib yang file had conflicting filename and internal yang revision.
  * This was only detected in the use-case when a whole dir was loaded.
  * Inserted sanity check in all yang parse routines.
  * Committed updated clixon-lib yang file that triggered the error
Thanks for detecting
