### ISSUE TITLE
Can clixon_netconf receive netconf packets as a server?

### ISSUE THREAD

**Issue by bearfirstrun** [clicon/clixon#93]
Hi @olofhagsand
I have a problem now, can you help me?

I want to use clixon_netconf as the server, netopeer_cli as the client on two devices.  I run the following command on netopeer(client), but always the connection is failed：
        netopeer-cli
        netconf> connect --login root --port 22 192.168.10.2
        root@192.168.10.2 password:
        libnetconf ERROR: Input channel error (end of file)
        connect: connecting to the 192.168.10.2:22 as user "root" failed.

I have registered  the subsystem netconf in /etc/ssh/sshd_config and installed openssh and libssh. But after netopeer_cli sends hello message ,it recieves hello message, then ERROR(This part of code is in libnetconf). 

In the file netconfi_main.c, sockfd=0(stdin) is listened always. 
So can netconf be used as a server to receive netconf client messages? Can clixon_netconf only receive input from the terminal?
If clixon_netconf can be used as a netconf server, why it report an error? 

Any kind of help would be appreciable.

Regards,
bearfirstrun

**Comment by olofhagsand** [comment]
There seems to be multiple issues. 
First, have you registered clixon_netconf as a ssh subserver server properly as described in:
  https://github.com/clicon/clixon/blob/master/doc/FAQ.md#how-do-i-use-netconf
ie with: 
```
Subsystem netconf /usr/local/bin/clixon_netconf -f /usr/local/etc/example.xml
```

Second, clixon_netconf is designed to be used as a subsystem with redirected stdin/stdout. It _could_ be extended as a proper server (as clixon_restconf / clixon_backend), it would just be to add proper daemon spawning code (ie needs implementation)

Third, for debugging, run clixon_netconf with -D 1 and check syslog to get error messages to see (maybe) where the error is.

Fourth, I havent run netopeer in this way. Can you provide simple instructions to run it in this way?

**Comment by bearfirstrun** [comment]
Hi, @olofhagsand
I have registered netconf as a ssh subsystem correctly and restart ssh service. On the both device, I installed openssh and libssh. 

I run clixon_netconf with -D 1 and then connect , but the clixon_netconf process has no response. Even after I kill the clixon_netconf process, the connect operation still has the same error. In addition, netopeer_cli sends the netconf hello message to ssh port 22, while clixon_netconf listens on stdin. Can clixon_netconf receive the hello message? I'm confused. So , I guess the problem is due to the operations of establishing ssh channel and request netconf subsystem, and hello-replay. But actually I dont know why?

My simple instruction:
                   dev1                                                                dev2                
         ---------------------                                       --------------------- 
        |   openssh/libssh  |                                      | openssh/libssh      |
        |                             |                                      |   clixon_backend   |
        |     netopeer_cli     |                                     |   clixon_netconf     |
        |     192.168.10.3     |  ----------------------  |  192.168.10.2        | 
         ---------------------                                       ---------------------         
dev1/2 : centos 7
perform clixon_backend
perform clixon_netconf :  blocking
perform netopeer_cli: netconf> connect --login root --port 22 192.168.10.2
                                    root@192.168.10.2 password:
then , error: libnetconf ERROR: Input channel error (end of file)
                    connect: connecting to the 192.168.10.2:22 as user "root" failed.
debug netopeer_cli, errror occurs atfer netopeer_cli  sending hello successfully.
clixon_netconf is still blocking.

**Comment by olofhagsand** [comment]
Try raw input using ssh first, eg:
  ssh -s 192.168.10.2 netconf
If that starts clixon_netconf, then your ssh sub-system is OK (sshd
forks clixon_netconf and redirects input on port 22 to clixon_netconf stdin)
If not, there is something wrong with the ssh subsystem setup.
--Olof

**Comment by bearfirstrun** [comment]
Hi, @olofhagsand
Thank you very much for your help.

I still haven't found the cause of the problem above,  but when clixon is installed by an RPM package, the connection is successful.  

Now I need your help with another difficulty :
When I make pkg-rpm,  the size of debuginfo.rpm  generated  is 0 , why is this ? 
What could  I do to use debuginfo.rpm to debug clixon_netconf  program ？

Thank you again！

**Comment by bearfirstrun** [comment]
I'm really sorry to bother you.  The difficulty just now has been solved. I add in the clixon.spec file:
                         %configure --with-cligen=%{cligen_prefix} --enable-debug
then , xxx-debuginfo-xxx_dirty_xxx.rpm is generated.
Is this right?
Thank you!

**Comment by bearfirstrun** [comment]
Hi, @olofhagsand
I installed clixon by building RPM and connection is OK.  
The previous problem still exists. I plan to solve it later.
Now, I find a mistake. I'm not sure whether it is a bug ?
In function "netconf_create_hello" of clixon/apps/netconf/netconf_hello.c 
    cprintf(cb, "<capability>urn:ietf:params:netconf:capability:candidate:1:0</capability>");
Should the above code be changed to :
    cprintf(cb, "<capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>");
That is 1:0 ---> 1.0 ?

Thank you!

**Comment by bearfirstrun** [comment]
HI, @dcornejo 
Sorry, I didn't notice the name before. Please see my above reply.
Thank you!

**Comment by olofhagsand** [comment]
Oops. Yes thanks for detecting, I will submit a patch on master asap.

**Comment by olofhagsand** [comment]
Outdated discussion
