### ISSUE TITLE
example/hello restconf demo doesn't work

### ISSUE THREAD

**Issue by nwpucong** [clicon/clixon#95]
http://localhost/restconf/  it says "Unsupported Media Type"

$ curl -X POST http://localhost/restconf/data -d '{"clixon-hello:hello":{"world":null}}'
Unsupported Media Type
$ curl -X GET http://localhost/restconf/data
{
  "data": null
}

**Comment by olofhagsand** [comment]
Try `curl -X POST http://localhost/restconf/data -H "Content-Type: application/yang-data+json" -d '{"clixon-hello:hello":{"world":null}}'`

**Comment by olofhagsand** [comment]
I updated the documentation to reflect you need the -H option to curl.
Should work now.
