### ISSUE TITLE
xml_parse_string() is slow for a long XML string

### ISSUE THREAD

**Issue by achernavin22** [clicon/clixon#96]
For example, if `xml_parse_string()` needs to parse a string like this, it takes several minutes:
```
<rpc-reply>
 <stdout><![CDATA[

... ~2MB of data ...

]]></stdout>
</rpc-reply>
```

Please find this XML string attached:
[xml_parse_string_long.txt](https://github.com/clicon/clixon/files/3845383/xml_parse_string_long.txt)

**Comment by olofhagsand** [comment]
Should be faster now, thanks for reporting
